novasamatech/nova-wallet-ios

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/DispatchQueueHelper.swift
novawallet/Common/Services/BaseSyncService.swift
novawallet/Common/Services/Multistaking/Multistaking+Model.swift
novawallet/Common/Services/Multistaking/Multistaking+Parachain.swift
novawallet/Common/Services/Multistaking/MultistakingRepositoryFactory.swift
novawallet/Common/Services/Multistaking/MultistakingSyncService.swift
novawallet/Common/Services/Multistaking/MultistakingSyncState.swift
novawallet/Common/Services/Multistaking/OffchainMultistakingUpdateService.swift
novawallet/Common/Services/Multistaking/ParachainMultistakingUpdateService.swift
novawallet/Common/Services/Multistaking/RelaychainMultistakingUpdateService.swift
novawallet/Common/Services/ObservableSyncService.swift
novawallet/Common/Storage/EntityToModel/StakingDashboardOffchainMapper.swift
novawallet/Common/Storage/EntityToModel/StakingDashboardParachainMapper.swift
novawallet/Common/Storage/EntityToModel/StakingDashboardRelaychainMapper.swift
novawallet/Common/Storage/EntityToModel/StakingResolvedAccountMapper.swift
novawallet/Common/Substrate/Types/ParachainStaking/ParachainStakingCandidateMetadata.swift
novawallet/Modules/Staking/Operations/ParachainStaking/ParaStkCollatorsOperationFactory.swift
novawallet/Modules/Staking/Parachain/ParaStkYourCollators/ViewModel/CollatorSelectionInfo+ViewModel.swift
novawalletIntegrationTests/MultistakingSyncTests.swift

- add parachain data sync service
- add option to subscribe to the syncing state

Sync parachain data #864en98uj #864en98vp #864en98vp

---

novawallet/Common/Extension/UIKit/Style/UILabel+Style.swift
novawallet/Modules/OperationDetails/Model/OperationContractCallModel.swift
novawallet/Modules/OperationDetails/Model/OperationExtrinsicModel.swift
novawallet/Modules/OperationDetails/Model/OperationRewardModel.swift
novawallet/Modules/OperationDetails/Model/OperationSlashModel.swift
novawallet/Modules/OperationDetails/Model/OperationTransferModel.swift
novawallet/Modules/OperationDetails/OperationDetailsInteractor.swift
novawallet/Modules/OperationDetails/OperationDetailsViewController.swift
novawallet/Modules/OperationDetails/OperationDetailsViewFactory.swift
novawallet/Modules/OperationDetails/OperationDetailsViewLayout.swift
novawallet/Modules/OperationDetails/View/OperationDetailsContractView.swift
novawallet/Modules/OperationDetails/View/OperationDetailsTransferView.swift
novawallet/Modules/OperationDetails/ViewModel/OperationDetailsViewModel.swift
novawallet/Modules/OperationDetails/ViewModel/OperationDetailsViewModelFactory.swift
novawallet/Modules/OperationDetails/ViewModel/OperationTransferViewModel.swift

Added fiat to Operation details screen

---

novawallet/Common/Services/RemoteSubscription/Evm/ERC20/ERC20BalanceUpdateService.swift
novawallet/Common/Services/RemoteSubscription/Evm/Native/EvmNativeBalanceUpdateService.swift
novawallet/Modules/AssetList/View/AssetListTotalBalanceCell.swift
novawallet/Modules/TransactionHistory/Service/TransactionHistoryRemoteFetcher.swift

- enable buy feature for assets list
- don't wait operation until finished in the main thread

Enable buy & fixes

---

.gitignore
novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/Web3Name/Web3TransferRecipientRepositoryFactory.swift
novawallet/Common/ViewController/ModalPicker/ModalNetworksFactory.swift
novawallet/Common/ViewModel/RemoteImageViewModel.swift
novawallet/Common/Web3Names/BaseKiltTransferAssetRecipientRepository.swift
novawallet/Common/Web3Names/JsonCanonicalizer.swift
novawallet/Common/Web3Names/Web3TransferRecipientRepository.swift
novawallet/Modules/Transfer/View/AssetListChainControlView.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationReferendumVoters/View/DelegateInfoView.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationReferendumVoters/View/DelegationReferendumVotersViewController.swift

- increase tap area for destination chain selector
- enable scroll for long destination chains list
- make w3n names order fixed
- fix race condition image loading

Fix crosschain UI

---

.swiftlint.yml
novawallet.xcodeproj/project.pbxproj
novawallet/Common/Animation/ShimmeringAnimator.swift
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Extension/UIKit/ScrullableView+Animation.swift
novawallet/Common/Extension/UIKit/UIView+Shimmering.swift
novawallet/Common/Protocols/LoadingUpdatibleView.swift
novawallet/Common/Services/BaseSyncService.swift
novawallet/Common/Services/ObservableSyncService.swift
novawallet/Common/View/CollectionView/BlurredCollectionViewCell.swift
novawallet/Common/View/MultilineBalanceView.swift
novawallet/Common/View/ShimmeringLabel.swift
novawallet/Modules/AssetList/View/AssetListChainView.swift
novawallet/Modules/Staking/Dashboard/Model/StakingDashboardModel.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardPresenter.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardViewController.swift
novawallet/Modules/Staking/Dashboard/View/StakingDashboardActiveCell.swift
novawallet/Modules/Staking/Dashboard/View/StakingDashboardActiveDetailsView.swift
novawallet/Modules/Staking/Dashboard/View/StakingDashboardInactiveCell.swift
novawallet/Modules/Staking/Dashboard/ViewModel/StakingDashboardSection.swift
novawallet/Modules/Staking/Dashboard/ViewModel/StakingDashboardViewModel.swift
novawallet/Modules/Staking/Dashboard/ViewModel/StakingDashboardViewModelFactory.swift
novawallet/Modules/Staking/StakingMain/View/StakingStatusView.swift
novawallet/Modules/Vote/Governance/ReferendumDetails/View/BlurredView.swift

Feature loading state

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/TransactionHistory/TokenPriceCalculator.swift
novawallet/Common/Model/WalletHistoryFilter.swift
novawallet/Modules/TransactionHistory/Model/TransactionHistoryPhishingFilter.swift
novawallet/Modules/TransactionHistory/Model/TransactionHistoryViewModelFactory.swift
novawallet/Modules/TransactionHistory/TransactionHistoryPresenter.swift
novawallet/Modules/TransactionHistory/TransactionHistoryViewController.swift
novawallet/Modules/TransactionHistory/TransactionHistoryViewFactory.swift
novawallet/Modules/TransactionHistory/TransactionHistoryViewLayout.swift

- fix price calculation on the given timestamp #85ztb45k1
- hide zero amount transfers for ERC-20 #85ztb5e91
- fix call/module display order for Substrate extrinsic #85ztb467h
- hide filter for non utility and evm assets #85ztbug42

Fix transaction history

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Foundation/BigUInt+Scientific.swift
novawallet/Common/Extension/Foundation/String+ScientificInt.swift
novawallet/Common/Network/Subquery/Models/SubqueryMultistaking.swift
novawallet/Common/Network/Subquery/SubqueryMultistakingOperationFactory.swift
novawallet/Common/Services/Multistaking/MultistakingSyncServiceFactory.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardInteractor.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardViewFactory.swift
novawalletTests/Common/Extensions/ScientificStringParsing.swift
novawalletTests/Mocks/ModuleMocks.swift

- support scientific notation for BigUInt to properly parse Subquery responses
- fix case when adding wallet but staking screen have not been opened yet (no event can be received)

Fix scientific notation

---

novawallet.xcodeproj/project.pbxproj
novawallet.xcodeproj/xcshareddata/xcschemes/novawallet.xcscheme
novawallet/Common/Extension/Foundation/StakingDuration+Localizable.swift
novawallet/Common/Model/SubstrateAlias.swift
novawallet/Common/Substrate/Types/StorageCodingPath.swift
novawallet/Modules/Staking/Operations/EraCountdownOperationFactory/AuraEraOperationFactory.swift
novawallet/Modules/Staking/Operations/EraCountdownOperationFactory/BabeEraOperationFactory.swift
novawallet/Modules/Staking/Operations/EraCountdownOperationFactory/EraCountdown.swift
novawallet/Modules/Staking/StakingUnbondConfirm/StakingUnbondConfirmInteractor.swift
novawallet/Modules/Staking/StakingUnbondConfirm/StakingUnbondConfirmPresenter.swift
novawallet/Modules/Staking/StakingUnbondConfirm/StakingUnbondConfirmProtocols.swift
novawallet/Modules/Staking/StakingUnbondSetup/StakingUnbondSetupInteractor.swift
novawallet/Modules/Staking/StakingUnbondSetup/StakingUnbondSetupPresenter.swift
novawallet/Modules/Staking/StakingUnbondSetup/StakingUnbondSetupProtocols.swift
novawalletTests/Mocks/DataProviders/EraCountdownOperationFactoryStub.swift
novawalletTests/Mocks/ModuleMocks.swift
novawalletTests/Modules/Staking/StakingRewardDetails/StakingRewardDetailsTests.swift
novawalletTests/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsTests.swift

- calculate session progress based on BabeEpochIndex (nevertheless duration of the epoch and session are the same there might be cases when epoch is different from the session)
- display hours for the unbonding on Unboding flow

Fix era timers #85ztcg0gj

---

novawallet.xcodeproj/project.pbxproj
novawallet/Assets.xcassets/colors/background/colorChipsOnCardBackground.colorset/Contents.json
novawallet/Assets.xcassets/colors/border/colorCardActionsBorder.colorset/Contents.json
novawallet/Common/Extension/UIKit/Style/RoundedView+Style.swift
novawallet/Common/View/TriangularedView/BlurBackgroundView.swift
novawallet/Common/View/TriangularedView/OverlayBlurBackgroundView.swift
novawallet/Modules/AssetList/View/AssetListTotalBalanceCell.swift

- setup shadow for asset card
- fix background for locks chips
- fix background for actions

Fix assets design

---

novawallet/Common/View/GladingView/GladingCardView.swift
novawallet/Common/View/GladingView/GladingPatternModel.swift
novawallet/Common/View/GladingView/GladingPatternView.swift
novawallet/Common/View/GladingView/GladingRectModel.swift
novawallet/Common/View/GladingView/GladingRectView.swift
novawallet/Modules/AssetList/Base/AssetListBaseBuilder.swift
novawallet/Modules/AssetList/Models/AssetListBuilder.swift
novawallet/Modules/AssetList/View/AssetListTotalBalanceCell.swift

- support Y tilting for card pattern
- remove text & buttons movement on tilting
- process asset list updates in batches using scheduler

Fix improve card animation #85ztf8akb

---

novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Services/WalletConnect/WalletConnectMetadata.swift
novawallet/Modules/Transfer/TransferConfirm/CrossChain/TransferCrossChainConfirmPresenter.swift
novawallet/Modules/Vote/Governance/Operation/Delegations/GovernanceDelegateMetadataFactory.swift
novawallet/Modules/Vote/Governance/ReferendumSearch/ReferendumEmptySearchTableViewCell.swift
novawallet/Modules/Vote/Governance/Referendums/ReferendumsViewManager.swift
novawallet/Resources/governanceDApps.json

- open origin asset details for crosschan transfer #85zth46b1
- replace organisation for GitHub urls #85ztgg1fh
- fix empty state for referendums after filter applied #85ztd4fkk

Fix UI and links

---

novawallet/Common/Network/Subquery/Filter/SubqueryFilter.swift
novawallet/Common/Network/Subquery/Models/SubqueryMultistaking.swift
novawallet/Common/Network/Subquery/Models/SubqueryRewardData.swift
novawallet/Common/Network/Subquery/SubqueryMultistakingOperationFactory.swift
novawallet/Common/Network/Subquery/SubqueryRewardOperationFactory.swift
novawalletTests/Resources/rewardResponse.json

- take slashes into account for MultiStaking Dashboard
- use aggregation for Total Rewards Filter and take slashes into account #85zth4e5m

Fix rewards subquery request

---

novawallet/Modules/Staking/StakingRewardFilters/Model/Lenses.swift
novawallet/Modules/Staking/StakingRewardFilters/StakingRewardFiltersViewController.swift

- [iOS. Can't select first date as startDate](https://app.clickup.com/t/85ztjy9de)
- [iOS. Let user select the same date as start and end in custom rewards](https://app.clickup.com/t/85ztjy4r0)

Rewards filter improvements

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/NPoolsLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/Subscription/DecodedProviderTypes.swift
novawallet/Common/DataProvider/Subscription/NPoolsLocalStorageHandler.swift
novawallet/Common/DataProvider/Subscription/NPoolsLocalStorageSubscriber.swift
novawallet/Common/DataProvider/SubstrateLocalSubscriptionFactory.swift
novawallet/Common/Protocols/LocalStorageProviderObserving.swift
novawallet/Common/Protocols/RuntimeConstantFetching.swift
novawallet/Common/Services/Multistaking/PoolsMultistakingUpdateService.swift
novawallet/Common/Services/RemoteSubscription/Substrate/NominationPoolsAccountUpdatingService.swift
novawallet/Common/Services/RemoteSubscription/Substrate/NominationPoolsPoolSubscriptionService.swift
novawallet/Common/Services/RemoteSubscription/Substrate/NominationPoolsRemoteSubscriptionService.swift
novawallet/Common/Storage/LocalStorageKeyFactory.swift
novawallet/Common/Substrate/Types/NominationPools/NominationPools+CodingPath.swift
novawallet/Common/Substrate/Types/NominationPools/NominationPools.swift
novawallet/Common/Substrate/Types/Support/SupportPallet.swift
novawalletIntegrationTests/NominationPoolsSyncTests.swift

- add subscription for nomination pools global data: minJoinBond, lastPoolId
- add subscription for pool id data: bondedPool, rewardPool, subPools, metadata
- add subscription for staking of the pool account: stakingLedger, nominations

Nomination pools subscriptions

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Substrate/Types/ConstantCodingPath.swift
novawallet/Modules/Staking/Model/ConsesusType.swift
novawallet/Modules/Staking/Model/Relaychain/StakingSharedState+Duration.swift
novawallet/Modules/Staking/Operations/EraCountdownOperationFactory/AuraEraOperationFactory.swift
novawallet/Modules/Staking/Operations/StakingDuration/AuraSessionLengthOperationFactory.swift
novawallet/Modules/Staking/Operations/StakingDuration/AuraStakingDurationFactory.swift
novawallet/Modules/Staking/Services/StakingServiceFactory.swift
novawallet/Modules/Staking/StakingMain/StakingMainPresenterFactory.swift

Now SessionPeriod was removed from election's constants. And don't have a way to determine it in general way for Aura consensus type. So, we now need to define it per each chain with Aura consensus we support - currently we only have Aleph Zero

Fix Aleph Zero coundown timer #85ztmjd1a

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/Subscription/NPoolsLocalStorageSubscriber.swift
novawallet/Common/EventCenter/EventVisitor.swift
novawallet/Common/EventCenter/Events/EraNominationPoolsChanged.swift
novawallet/Common/Services/BaseSyncService.swift
novawallet/Common/Substrate/Types/NominationPools/NominationPools.swift
novawallet/Modules/Staking/Operations/NominationPools/NominationPoolsOperationFactory.swift
novawallet/Modules/Staking/Services/EraValidatorsService/EraNominationPoolsService.swift
novawallet/Modules/Staking/Services/EraValidatorsService/EraNominationPoolsServiceProtocol.swift
novawallet/Modules/Staking/Services/EraValidatorsService/Model/NominationPoolModel.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/NominationPools/NPoolsRewardEngineFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/NominationPools/NominationPoolsRewardEngine.swift
novawalletIntegrationTests/ActiveNominationPoolsTests.swift
novawalletIntegrationTests/NominationPoolsApyTests.swift

- add service that calculates all active pools based on lastPoolId or validators change
- add factory to create nomination pools reward calculator based on validators reward calculator

Calculate active pools and apy

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/Staking/Dashboard/StakingDashboardWireframe.swift
novawallet/Modules/Staking/Services/EraValidatorsService/Model/NominationPoolModel.swift
novawallet/Modules/Staking/StakingMoreOptions/StakingMoreOptionsWireframe.swift
novawallet/Modules/Staking/StakingSetupAmount/Model/StakingTypeBalanceFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/Recommendation/HybridStakingRecommendationMediator.swift
novawallet/Modules/Staking/StakingSetupAmount/Recommendation/StakingRecommendationMediatorFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountInteractor.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountPresenter.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountProtocols.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountViewController.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountViewFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountWireframe.swift
novawallet/Modules/Staking/StartStakingConfirm/ExtrinsicProxy/StartStakingExtrinsicProxy.swift
novawallet/Modules/Staking/StartStakingConfirm/ExtrinsicProxy/StartStakingFeeIdFactory.swift
novawallet/Modules/Staking/StartStakingConfirm/Presenter/StartStakingDirectConfirmPresenter.swift
novawallet/Modules/Staking/StartStakingConfirm/Presenter/StartStakingDirectConfirmWireframe.swift
novawallet/Modules/Staking/StartStakingConfirm/Presenter/StartStakingPoolConfirmPresenter.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmInteractor.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmInteractorError.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmPresenter.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmProtocols.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmViewController.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmViewFactory.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmViewLayout.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmWireframe.swift
novawallet/Modules/Staking/ViewModel/NominationPoolsIconFactory.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Start staking confirm

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Foundation/TimeInterval+Localization.swift
novawallet/Common/Extension/Foundation/TimeInterval+Time.swift
novawallet/Common/Helpers/PredefinedTimeShortcut.swift
novawallet/Common/Services/Multistaking/Multistaking+Model.swift
novawallet/Modules/Staking/Dashboard/Model/StakingDashboardBuilder.swift
novawallet/Modules/Staking/Dashboard/Model/StakingDashboardBuilderResult.swift
novawallet/Modules/Staking/Dashboard/Model/StakingDashboardModel.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardPresenter.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardProtocols.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardWireframe.swift
novawallet/Modules/Staking/Dashboard/ViewModel/StakingDashboardViewModelFactory.swift
novawallet/Modules/Staking/StakingMoreOptions/StakingMoreOptionsPresenter.swift
novawallet/Modules/Staking/StakingMoreOptions/StakingMoreOptionsProtocols.swift
novawallet/Modules/Staking/StakingMoreOptions/StakingMoreOptionsViewModelFactory.swift
novawallet/Modules/Staking/StakingMoreOptions/StakingMoreOptionsWireframe.swift
novawallet/Modules/Staking/StartStakingInfo/Model/StartStakingViewModelFactory.swift
novawallet/Modules/Staking/StartStakingInfo/ParachainStaking/StartStakingInfoParachainPresenter.swift
novawallet/Modules/Staking/StartStakingInfo/ParachainStaking/StartStakingParachainInteractor.swift
novawallet/Modules/Staking/StartStakingInfo/RelaychainStaking/StartStakingInfoRelaychainPresenter.swift
novawallet/Modules/Staking/StartStakingInfo/RelaychainStaking/StartStakingRelaychainInteractor.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoBasePresenter.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoConstants.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoViewController.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoViewFactory.swift
novawallet/Modules/Staking/StartStakingInfo/View/ParagraphView.swift
novawallet/Modules/Staking/StartStakingInfo/View/StartStakingInfoViewLayout.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

- fix dashboard logic with badges: show badge if more then 1 staking active for asset, don't show asset in more options if staking is inactive for the asset (not testnet), show badges for staking options in more options;
- fix timers update to properly display time dependent value;
- time formatters now display days and hours as on all the screens
- fix styles on the screen

Dashboard & start staking info improvements #85ztq9u8a

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Crypto/BaseSigner.swift
novawallet/Common/Crypto/EthereumSigner.swift
novawallet/Common/Crypto/SigningWrapper.swift
novawallet/Common/Crypto/SigningWrapperFactory.swift
novawallet/Common/Services/WalletConnect/WalletConnectService.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppEthereumSignBytesInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmViewFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppSignBytesConfirmInteractor.swift
novawalletTests/Modules/DApps/DAppOperationConfirm/DAppOperationConfirmTests.swift

- improve wallet connect reconnection handling #85ztr6mb0
- fix freezes on sign bytes when bio auth enabled #85ztqbdge
- add support for auth for ethereum sign bytes

Fix wc networking

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/Multistaking/PoolsMultistakingUpdateService.swift
novawallet/Common/Substrate/Types/NominationPools/NominationPools.swift
novawallet/Modules/Staking/Protocols/StakingErrorPresentable.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsInteractor.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsPresenter.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsProtocols.swift
novawallet/Modules/Staking/StakingMain/NominationPools/ViewModel/StakingNPoolsViewModelFactory+Alerts.swift
novawallet/Modules/Staking/StakingMain/NominationPools/ViewModel/StakingNPoolsViewModelFactory.swift
novawallet/Modules/Staking/StakingMain/NominationPools/ViewModel/StakingNominationPoolsStatics.swift
novawallet/Modules/Staking/StakingMain/StakingMainViewController.swift
novawallet/Modules/Staking/StakingMain/View/StakingUnbondingsView.swift
novawallet/Modules/Staking/StakingMain/ViewModel/StakingMainStaticViewModel.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

- add unstaking list for nomination pool details #85ztauw9c
- add alerts list for nomination pool details #85ztauw9g

Nomination pools unstaking widget & alerts

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Protocols/ExtrinsicSubmissionPresenting.swift
novawallet/Common/Substrate/Calls/NominationPools/NominationPoolsRedeemCall.swift
novawallet/Common/Substrate/Types/SlashingSpans.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemError.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemInteractor.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemPresenter.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemProtocols.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemViewController.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemViewFactory.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemViewLayout.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemWireframe.swift
novawallet/Modules/Staking/Operations/SlashesOperationFactory.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsWireframe.swift
novawallet/Modules/Staking/StakingRedeem/StakingRedeemInteractor.swift
novawalletTests/Mocks/DataProviders/SlashesOperationFactoryStub.swift

Nomination pool redeem #85ztp5r8w

---

novawallet/Modules/Staking/Model/Relaychain/PreparedNomination.swift
novawallet/Modules/Staking/NominationPoolSearch/NominationPoolSearchInteractor.swift
novawallet/Modules/Staking/NominationPoolSearch/NominationPoolSearchPresenter.swift
novawallet/Modules/Staking/NominationPoolSearch/NominationPoolSearchProtocols.swift
novawallet/Modules/Staking/NominationPoolSearch/NominationPoolSearchViewFactory.swift
novawallet/Modules/Staking/NominationPoolSearch/NominationPoolSearchViewLayout.swift
novawallet/Modules/Staking/Parachain/ParaStkCollatorsSearch/ParaStkCollatorsSearchWireframe.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeConfirm/ParaStkStakeConfirmPresenter+StartStaking.swift
novawallet/Modules/Staking/SelectValidatorsFlow/SelectedValidatorList/Wireframe/StartStakingSelectedValidatorsListWireframe.swift
novawallet/Modules/Staking/SelectValidatorsFlow/StaticValidatorList/StaticValidatorListViewFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/Recommendation/DirectStakingRecommendationFactory.swift
novawallet/Modules/Staking/StakingType/StakingTypePresenter.swift
novawallet/Modules/Staking/StartStakingConfirm/ExtrinsicProxy/StartStakingExtrinsicProxy.swift
novawallet/Modules/Staking/StartStakingConfirm/StartStakingConfirmViewLayout.swift

- fix parachain staking search from start staking flow #85ztu8tee
- remove hints from parachain start staking confirm screen #85ztuga2h
- fix validator search for case when found validator is not including to the final list
- improve pool search on bad connection #85ztvqebj

Fix parachain flow & search colator/validators

---

novawallet/Modules/OperationDetails/ViewModel/OperationDetailsViewModelFactory.swift

Fix non utility token transfer fee #85ztz8txy

---

novawallet/Modules/Staking/Parachain/Model/CollatorsSortType.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeConfirm/ParaStkStakeConfirmWireframe.swift
novawallet/Modules/Staking/StakingMain/Parachain/StakingParachainPresenter.swift

- fix taping on alerts in the parachain staking can lead to a wrong flow #85ztz97x7
- fix return to the dashboard after parachain start staking flow #85ztz97rh
- fix collators sort by min stake #85ztz983y

Fix parachain staking

---

novawallet/Common/Ledger/SupportedLedgerApps.swift

add Aleph Zero ledger support #85ztt1vja

---

novawallet/Modules/ParitySigner/TransactionQr/ParitySignerTxQrInteractor.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendumTimelineViewModelFactory.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendumsViewModelFactory/ReferendumsModelFactory+State.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Replace negative not passing status with neutral deciding status #85ztz40x0

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTransferService+Compose.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTransferService.swift
novawallet/Common/Substrate/Calls/XTokens/XTokensTransfer.swift
novawallet/Common/Substrate/Types/XTokens/XTokens.swift
novawallet/Common/Substrate/Types/XTokens/XTokensMetadataQueryFactory.swift
novawallet/Common/Substrate/Types/Xcm/XcmBaseMetadataQueryFactory.swift
novawallet/Common/Substrate/Types/Xcm/XcmPalletMetadataQueryFactory.swift

- add support for different xtokens pallet naming - XTokens, Xtokens

Support xcm transfers from Astar #8692rx887

---

novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Operation/MultipartQrOperationFactory.swift
novawallet/Common/Protocols/BaseErrorPresentable.swift
novawallet/Common/Validation/Validators/BaseDataValidatorFactory.swift
novawallet/Modules/Staking/NominationPools/BondMore/Base/NominationPoolBondMoreBaseInteractor.swift
novawallet/Modules/Staking/NominationPools/ClaimRewards/Model/NPoolsClaimRewardsError.swift
novawallet/Modules/Staking/NominationPools/ClaimRewards/NPoolsClaimRewardsInteractor.swift
novawallet/Modules/Staking/NominationPools/ClaimRewards/NPoolsClaimRewardsPresenter.swift
novawallet/Modules/Staking/NominationPools/ClaimRewards/NPoolsClaimRewardsProtocols.swift
novawallet/Modules/Staking/NominationPools/ClaimRewards/NPoolsClaimRewardsViewFactory.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemError.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemInteractor.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemPresenter.swift
novawallet/Modules/Staking/NominationPools/Redeem/NPoolsRedeemProtocols.swift
novawallet/Modules/Staking/NominationPools/Unstake/Base/NPoolsUnstakeBaseError.swift
novawallet/Modules/Staking/NominationPools/Unstake/Base/NPoolsUnstakeBaseInteractor.swift
novawallet/Modules/Staking/NominationPools/Unstake/Base/NPoolsUnstakeBasePresenter.swift
novawallet/Modules/Staking/NominationPools/Unstake/Base/NPoolsUnstakeBaseProtocols.swift
novawallet/Modules/Staking/Parachain/ParaStkRedeem/ParaStkRedeemInteractor.swift
novawallet/Modules/Staking/Parachain/ParaStkRedeem/ParaStkRedeemPresenter.swift
novawallet/Modules/Staking/Parachain/ParaStkRedeem/ParaStkRedeemProtocols.swift
novawallet/Modules/Staking/Parachain/ParaStkRedeem/ParaStkRedeemWireframe.swift
novawallet/Modules/Staking/StakingMain/View/NominatorStateView.swift
novawallet/Modules/Staking/StakingMain/View/StakingStateView.swift
novawallet/Modules/Staking/StakingMain/View/StakingTotalRewardView.swift
novawallet/Modules/Staking/StakingMain/View/ValidatorStateView.swift
novawallet/Modules/Transfer/Validation/TransferDataValidatorFactory.swift
novawallet/Modules/Transfer/Validation/TransferErrorPresentable.swift

- move to dashboard after parachain staking redeem all #85ztzapq0
- add existential deposit validation for nomination pool unstake, claim and redeem operations #8692t0fat
- fix staking details shimmering #85ztyd3wp
- set payload size = 512 for multiframe QR code #8692rur7h
- bump xcm config #8692t19ae

Fix staking bugs & release preparation

---

novawallet/Modules/AssetDetails/AssetDetailsInteractor.swift
novawallet/Modules/Staking/Parachain/ParaStkRedeem/ParaStkRedeemPresenter.swift

- fix corner case when redeem all from the parachain staking
- fix crash when returning from Asset Details

Fix redeem all from parachain & crash fix

---

novawallet/Modules/Staking/Model/Relaychain/ElectedAndPrefValidators.swift
novawallet/Modules/Staking/Model/Relaychain/PreparedNomination.swift
novawallet/Modules/Staking/Model/Relaychain/SelectedStakingOption.swift
novawallet/Modules/Staking/Services/EraValidatorsService/Model/NominationPoolModel.swift
novawallet/Modules/Staking/StakingType/StakingTypePresenter.swift

Added equatable implementation for staking option

Done has disabled state if staking type has no changes 

---

novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteAssetModel+Evm.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteEvmToken.swift
novawalletTests/Helper/ChainModelGenerator.swift

Support buy providers for erc-20 tokens

---

novawallet/Common/ViewController/SearchController/BaseTableSearchViewLayout.swift
novawallet/Modules/Staking/NominationPoolSearch/NominationPoolSearchViewController.swift
novawallet/Modules/Staking/Parachain/ParaStkCollatorsSearch/ParaStkCollatorsSearchViewController.swift
novawallet/Modules/Staking/SelectValidatorsFlow/ValidatorSearch/ValidatorSearchViewController.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateSearch/GovernanceDelegateSearchViewController.swift
novawallet/Modules/Vote/Governance/ReferendumSearch/ReferendumSearchViewLayout.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Fix search style

---

novawallet/Common/Helpers/KeyboardAppearanceState.swift
novawallet/Modules/AssetsSearch/AssetOperation/AssetOperationViewFactory.swift
novawallet/Modules/AssetsSearch/AssetSearch/AssetsSearchViewController.swift

**Buy flow**
Initial state:
Searching state:

Hide keyboard when a user selects cell for Send, Receive, Buy flows

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Model/AssetStorageInfo.swift
novawallet/Common/Model/StateminAssetExtras.swift
novawallet/Common/Operation/StorageKeyEncodingOperation.swift
novawallet/Common/Services/RemoteSubscription/Substrate/RemoteSubscriptionRequests.swift
novawallet/Common/Services/RemoteSubscription/Substrate/WalletRemoteSubscriptionService.swift
novawallet/Common/Services/RemoteSubscription/Substrate/WalletRemoteSubscriptionWrapper.swift
novawallet/Common/Services/WebSocketService/StorageSubscription/ExtrinsicProcessing.swift
novawallet/Common/Services/WebSocketService/StorageSubscription/ExtrinsicProcessor+Matching.swift
novawallet/Common/Substrate/Calls/Assets/PalletAssets+Call.swift
novawallet/Common/Substrate/Calls/Common/AssetsTransfer.swift
novawallet/Common/Substrate/Calls/Common/SubstrateCallFactory.swift
novawallet/Common/Substrate/Types/AssetConversionPallet/AssetConversionPallet.swift
novawallet/Common/Substrate/Types/CallCodingPath.swift
novawallet/Modules/AssetConversion/Service/AssetHub/AssetHubSwapOperationFactory.swift
novawallet/Modules/AssetConversion/Service/AssetHub/AssetHubTokensConverter.swift
novawallet/Modules/Transfer/BaseTransfer/OnChain/OnChainTransferInteractor.swift
novawallet/Modules/Transfer/Operation/AssetStorageInfoOperationFactory.swift

Foreign assets support for transfers and swap #8692v6hmj

---

novawallet/Common/PurchaseProvider/PurchaseAggregator+Default.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Improve Buy disclaimer & order

---

novawallet/Modules/AssetsSearch/Swaps/SwapAssetsOperationViewFactory.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Swaps: Select token to receive screen

---

novawallet/Modules/AssetList/Base/AssetListBaseBuilder.swift
novawallet/Modules/Nft/NftList/NftListInteractor.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardInteractor.swift
novawallet/Modules/Vote/Crowdloan/CrowdloanYourContributions/CrowdloanYourContributionsInteractor.swift

- fix issue when all tokens are spent but the amount is not updated on the asset search/send #8692zwbwq
- fix crash when last wallet is removed from the app
- fix crash on fast open/close NftList screen
- fix crash on fast open/close YourContributions screen

Fix balance update after transfer all and crashes

---

novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Modules/Vote/Crowdloan/Operation/ExternalContibution/AcalaContributionSource.swift
novawallet/Modules/Vote/Crowdloan/Operation/ExternalContibution/ParallelContributionSource.swift

- disable parallel endpoint
- remove Acala record instead of putting zero
- bump chains to v15

Disable parallel endpoint

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Foundation/String+Helpers.swift
novawallet/Modules/Swaps/Base/SwapPriceDifferenceViewModelFactoryProtocol.swift
novawallet/Modules/Swaps/Confirm/Model/SwapConfirmViewModelFactory.swift
novawallet/Modules/Swaps/Setup/Model/SwapsSetupViewModelFactory.swift
novawallet/Modules/Swaps/Setup/Model/ViewModels.swift
novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift
novawallet/Modules/Swaps/Setup/SwapSetupProtocols.swift
novawallet/Modules/Swaps/Setup/SwapSetupViewController.swift
novawallet/Modules/Swaps/Setup/SwapSetupViewFactory.swift
novawallet/Modules/Swaps/Setup/View/SwapAmountInput.swift
novawallet/Modules/Swaps/Setup/View/SwapAmountInputView.swift

Swaps: price difference in setup

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/AssetsSearch/Swaps/SwapAssetOperationPresenter.swift
novawallet/Modules/AssetsSearch/Swaps/SwapAssetsOperationInteractor.swift
novawallet/Modules/AssetsSearch/Swaps/SwapAssetsOperationProtocols.swift
novawallet/Modules/AssetsSearch/Swaps/SwapAssetsOperationViewFactory.swift
novawallet/Modules/AssetsSearch/Swaps/SwapSelectedChainAsset.swift
novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift
novawallet/Modules/Swaps/Setup/SwapSetupProtocols.swift
novawallet/Modules/Swaps/Setup/SwapSetupWireframe.swift

Show edit icon in fee cell for self-sufficient pay asset

Swaps: show fee asset selection for self-sufficient tokens only

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicServiceFactory.swift
novawallet/Common/Substrate/Extension/AssetConversionTxPayment.swift
novawallet/Common/Substrate/Extension/ExtrinsicExtension.swift
novawallet/Modules/Swaps/Confirm/Model/SwapConfirmViewModelFactory.swift
novawallet/Modules/Swaps/Confirm/SwapConfirmInteractor.swift
novawallet/Modules/Swaps/Confirm/SwapConfirmProtocols.swift
novawallet/Modules/Swaps/Confirm/SwapConfirmViewFactory.swift
novawallet/Modules/Swaps/Confirm/View/SwapConfirmViewLayout.swift
novawallet/Modules/Swaps/Setup/Model/SwapsSetupViewModelFactory.swift
novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift
novawallet/Modules/Swaps/Setup/View/SwapSetupViewLayout.swift

Allow fee payment in custom token #8692tuwq8

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Substrate/Calls/UtilityPallet/Utility+Calls.swift
novawallet/Common/Substrate/Types/UtilityPallet/UtilityPallet.swift
novawallet/Modules/Vote/Governance/Model/ReferendumActionLocal.swift
novawallet/Modules/Vote/Governance/Operation/Action/GovernanceActionOperationFactory.swift
novawallet/Modules/Vote/Governance/Operation/Action/Parser/GovSpentAmountBatchHandler.swift
novawallet/Modules/Vote/Governance/Operation/Action/Parser/GovSpentAmountExtractor.swift
novawallet/Modules/Vote/Governance/Operation/Action/Parser/GovTreasuryApproveHandler.swift
novawallet/Modules/Vote/Governance/Operation/Action/Parser/GovTreasurySpentAmountHandler.swift
novawallet/Modules/Vote/Governance/ReferendumDetails/ReferendumDetailsPresenter.swift
novawallet/Modules/Vote/Governance/ReferendumFullDetails/ReferendumFullDetailsPresenter.swift

Support batch call when extracting requested amount for referendum 86933jup3

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/URLHandling/Parsing/OpenDAppUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenScreenUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenScreenUrlParsingServiceFactory.swift
novawallet/Common/URLHandling/ScreenOpenService.swift
novawallet/Modules/DApp/DAppList/DAppListPresenter.swift
novawallet/Modules/DApp/DAppList/DAppListProtocols.swift
novawallet/Modules/DApp/DAppList/DAppListViewController.swift
novawallet/Modules/MainTabBar/MainTabBarWireframe.swift

Action: xcrun simctl openurl booted "novawallet://nova/open//dapp?url="https://polkadot.polkassembly.io/""

Deeplinks: Open dapp screen by deeplink #86934jpye 

---

novawallet/Common/URLHandling/KeystoreImportService.swift
novawallet/Common/URLHandling/Parsing/ImportWalletUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenDAppUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenGovernanceUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenScreenUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenStakingUrlParsingService.swift
novawallet/Common/URLHandling/ScreenOpenService.swift
novawallet/Modules/AccountImport/BaseAccountImportInteractor.swift
novawallet/Modules/MainTabBar/MainTabBarInteractor.swift
novawallet/Modules/MainTabBar/MainTabBarPresenter.swift
novawallet/Modules/MainTabBar/MainTabBarProtocol.swift
novawallet/Modules/MainTabBar/MainTabBarViewFactory.swift
novawallet/Modules/MainTabBar/MainTabBarWireframe.swift
novawallet/Modules/OnbordingMain/OnboardingMainInteractor.swift
novawallet/Modules/OnbordingMain/OnboardingMainPresenter.swift
novawallet/Modules/OnbordingMain/OnboardingMainProtocol.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Deeplinks: Show errors

---

Podfile.lock
novawallet/Common/Network/Subquery/SubqueryHistoryOperationFactory.swift

Hotfix: Subquery history status

---

novawallet/Common/Operation/StorageDecodingOperation.swift
novawallet/Common/Services/Proxy/ChainProxySyncService.swift
novawallet/Common/Services/Proxy/ProxyOperationFactory.swift
novawallet/Common/Services/StorageQueryService/StorageRequestFactory.swift
novawalletIntegrationTests/Proxy/ProxySyncIntegrationTests.swift

- add ignoresFailedItem flag to list decoding operation;
- introduce StorageQueryListOptions struct to provide settings for the query;

Fix proxy parsing on polkadot

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Protocols/WebPresentable.swift
novawallet/Common/Services/Proxy/ChainProxyChangesCalculator.swift
novawallet/Common/Services/Proxy/ChainProxySyncService.swift
novawallet/Common/Services/Proxy/ProxyModels.swift
novawallet/Common/Services/Proxy/ProxyOperationFactory.swift
novawallet/Modules/Proxy/ProxiedsUpdate/ProxiedsUpdatePresenter.swift
novawallet/Modules/Proxy/ProxiedsUpdate/ProxiedsUpdateViewController.swift
novawallet/Modules/Proxy/ProxiedsUpdate/View/ProxyUpdateStyle.swift
novawallet/Modules/WalletsList/Common/WalletView.swift
novawallet/Modules/WalletsList/Common/WalletsListViewModelFactory.swift
novawallet/Modules/WalletsList/Manage/WalletManagePresenter.swift
novawallet/Modules/WalletsList/Selection/WalletSelectionPresenter.swift
novawallet/Modules/WalletsList/Selection/WalletSelectionViewController.swift
novawallet/Modules/WalletsList/Selection/WalletSelectionViewProtocols.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings
novawalletTests/Mocks/ModuleMocks.swift

- ignore nested proxies 8693empad 8693ek0tc
- skip delayed proxies 8693ewxxq
- fix text in wallet settings 8693ezbe1
- apply updates only after wallets selection is closed 8693ek5a9
- proxieds section must be displayed before watch only in the wallets list 8693ejket
- fix display update for revoked proxies 8693ehae5
- add proxy wiki link 8693f57d3

Fix proxy bugs

---

novawallet/Modules/Staking/StakingMain/Relaychain/StakingRelaychainInteractor+Subscription.swift
novawallet/Modules/Staking/StakingMain/Relaychain/StakingRelaychainPresenter.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Proxy: controller alert

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/CancellableCallHelper.swift
novawallet/Common/Model/KnownChainIds.swift
novawallet/Modules/Staking/Model/StakingConstants.swift
novawallet/Modules/Staking/Operations/ParachainStaking/ParaStkPreferredCollatorFactory.swift
novawallet/Modules/Staking/Parachain/Model/CollatorsSortType.swift
novawallet/Modules/Staking/Parachain/ParaStkSelectCollators/ParaStkSelectCollatorsPresenter.swift
novawallet/Modules/Staking/Parachain/ParaStkSelectCollators/ParaStkSelectCollatorsViewFactory.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupInteractor.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupPresenter.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupProtocols.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupViewFactory.swift

Add preferred collators for parachain staking 8693kumw0

---

novawallet/Modules/Vote/Governance/Operation/Action/Gov2ActionOperationFactory.swift

We expected that preimage pallet migrates the ```statusFor``` storage to the ```requestStatusFor``` storage. This didn't happen so we now need to support new storage and deprecated one.

Fix preimage backport

---

novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/InflationCurveRewardConfig.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorEngineFactory.swift
novawallet/Modules/Vote/Governance/Operation/Action/Gov2ActionOperationFactory.swift

- change parachain reserve coefficient to 0.2 for Polkadot #8693n5wak
- fix polkadot-vault and parity signer troubleshooting links #8693myyfk

Fix polkadot apy

---

novawallet/Modules/Staking/StakingMain/Relaychain/StakingRelaychainInteractor+Subscription.swift

No "Add delegated authority" for controller account

Bugfix: Add delegated authority 

---

novawallet/Info.plist

App Store submission now requires manual provision of the policies to the Info.plist

Fix appstore usage

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/Notifications/NotificationHandlers/CaseInsensitiveDecodale.swift
novawallet/Modules/Notifications/NotificationHandlers/Payload.swift

Bug fix: Governance push notification

---

novawallet/Common/Substrate/Types/HydraDx/HydraAssetRegistry+Storages.swift
novawallet/Common/Substrate/Types/HydraDx/HydraAssetRegistry.swift
novawallet/Modules/AssetConversion/Service/HydraDx/Stableswap/HydraStableswapReserversRemoteState.swift
novawallet/Modules/AssetConversion/Service/HydraDx/Stableswap/HydraStableswapReservesService.swift

- support renaming merging asset metadata with asset storages for HydraDX

Fix HydraDx runtime upgrade breaking change

---

novawallet.xcodeproj/project.pbxproj
novawallet.xcodeproj/xcshareddata/xcschemes/novawallet.xcscheme
novawallet/Common/EventCenter/EventVisitor.swift
novawallet/Common/EventCenter/Events/AccountsRemovedManually.swift
novawallet/Common/Services/ServiceCoordinator.swift
novawallet/Common/Services/Web3AlertService/PushNotificationsFacadeFactory.swift
novawallet/Common/Services/Web3AlertService/PushNotificationsServiceFacade.swift
novawallet/Common/Services/Web3AlertService/Web3AlertsSyncService.swift
novawallet/Common/Services/Web3AlertService/Web3AlertsWalletsUpdateService.swift
novawallet/Modules/MainTabBar/MainTabBarInteractor.swift
novawallet/Modules/WalletsList/Manage/WalletManageInteractor.swift
novawalletTests/Mocks/ModuleMocks.swift

- add logic to automatically sync push notifications settings when a wallet is removed/changed

Sync push notification wallets

---

novawallet/Modules/MainTabBar/MainTabBarWireframe.swift
novawallet/Modules/Notifications/Management/NotificationsManagementInteractor.swift
novawallet/Modules/Notifications/Management/NotificationsManagementPresenter.swift
novawallet/Modules/Notifications/Setup/NotificationsSetupViewLayout.swift
novawallet/Modules/Settings/SettingsPresenter.swift
novawallet/Modules/Settings/SettingsProtocols.swift
novawallet/Modules/Settings/SettingsWireframe.swift

- removed setup from settings
- removed close button and swipe down gesture

Improve setup push notifications 

---

novawallet/Modules/Transfer/BaseTransfer/CrossChain/CrossChainTransferPresenter.swift
novawallet/Modules/Transfer/Validation/TransferDataValidatorFactory.swift

Don't allow going below ed for crosschain transfers

Fix delivery fee validation for xcm

---

novawallet/Common/DataProvider/PriceProviderFactory.swift
novawallet/Common/DataProvider/Sources/CoingeckoPriceHistorySource.swift

- limit coingecko history price fetch by 365 days

Fix coingecko api 869496fc6

---

novawallet/Common/DataProvider/PriceProviderFactory.swift
novawallet/Common/DataProvider/Sources/CoingeckoPriceHistorySource.swift
novawallet/Common/Network/GovMetadataOperationFactory/Subsquare/BaseSubsquareOperationFactory.swift
novawallet/Modules/Vote/Governance/Referendums/ReferendumsInteractor+Protocol.swift
novawallet/Modules/Vote/Governance/Referendums/ReferendumsPresenter.swift
novawallet/Modules/Vote/Governance/Referendums/ReferendumsProtocols.swift

- fetch last 100 gov metadata item from Subsquare api
- refresh items referendums list opens instead of each block

Fix subsquare api 86949hhw4

---

novawallet/Common/Configs/ApplicationConfigs.swift

Thats time to switch to our infra:
https://grafana.k8s-1.novasama.co/d/cdh5gd24cofeod/subquery?orgId=1&refresh=1m&var-project=subquery-multi-staking&var-env=prod

feat: switch multichain url

---

novawallet/Common/Services/PayoutRewardsService/UnclaimedRewards/StakingUnclaimedRewardsFacade.swift

If eraStakersOverview exists then the logic takes both unclaimed rewards from ```staking.ledger.legacyClaimedRewards``` and from ```staking.claimedRewards``` storage. If there is an unclaimed reward in the new storage then we also check that it is unclaimed in the legacy storage.

Fix unclaimed rewards

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Foundation/Decimal+Conversion.swift
novawallet/Common/Model/KnownChainIds.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorEngineFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorParamsService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorParamsServiceFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/VaraRewardEngine.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/VaraRewardParamsService.swift

Add vara reward calculation engine

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Network/Staking/StakingGlobalConfigProvider.swift
novawallet/Common/Network/Subquery/SubqueryMultistakingProxy.swift
novawallet/Common/PurchaseProvider/PurchaseAggregator+Default.swift
novawallet/Common/Services/Multistaking/MultistakingSyncServiceFactory.swift
novawallet/Common/Services/PayoutRewardsService/PayoutRewardsService+Fetch.swift
novawallet/Common/Services/Web3AlertService/Model/PushNotificationSettingsFactory.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardViewFactory.swift
novawallet/Modules/Staking/Model/StakingConstants.swift
novawalletIntegrationTests/MultistakingSyncTests.swift
novawalletIntegrationTests/SubqueryMultistakingTests.swift

- add staking global config provider to fetch multitasking config from remote #8694e6quw
- fix validator prefs fetching issue for staking unpaid rewards
- changed purchase providers order #8694e6rg1
- enable staking push notifications by default #8694e6r9e
- add vara pool

v7.12 remained

---

NovaPushNotificationServiceExtension/PrivacyInfo.xcprivacy
novawallet.xcodeproj/project.pbxproj
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Modules/Staking/SelectValidatorsFlow/SelectValidatorsStart/SelectValidatorsStartInteractor.swift
novawallet/PrivacyInfo.xcprivacy

- fix crash when returning back from validators screen #8694fuz8c
- bump chains to v19
- add privacy manifest for UserDefaults usage

Fix release bugs

---

novawallet/Modules/Staking/Operations/ValidatorOperationFactory/ValidatorOperationFactory.swift
novawallet/Modules/Staking/Services/EraValidatorsService/Validators/EraValidatorsUpdating.swift

- assume empty list if eraStakersPaged doesn't contain pages
- fix crash if activeEra less then number of slash eras
##

fix avail validators fetch

---

Podfile
Podfile.lock
novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/KnownChainIds.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionFactory.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionTransportFactory.swift

- replace transport for Mythos network that support TLSv1.3

Fix mythos connection

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/ChainRegistry/LocalChain/ChainNodeModel.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionFactory.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionTLSSupportProvider.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionTransportFactory.swift

The aim of the PR is to be able to switch transports for the web sockets automatically based on the node's feature of support tls 1.2

Dynamic switch transport for connection

---

novawallet/Common/Substrate/Types/Referenda/Referenda.swift
novawallet/Common/Substrate/Types/Referenda/ReferendaTrackInfo.swift
novawallet/Modules/Notifications/GovernanceTracksSettings/GovernanceTracksSettingsPresenter.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationTracks/AddDelegationTracks/GovernanceAddDelegationTracksPresenter.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationTracks/EditDelegationTracks/GovernanceEditDelegationTracksPresenter.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationTracks/RevokeDelegationTracks/GovernanceRevokeDelegationTracksPresenter.swift
novawallet/Modules/Vote/Governance/GovernanceSelectTracks/Base/SelectTracksPresenter.swift
novawallet/Modules/Vote/Governance/GovernanceSelectTracks/GovernanceSelectTracksPresenter.swift
novawallet/Modules/Vote/Governance/GovernanceSelectTracks/ViewModel/GovernanceSelectTrackViewModel.swift
novawallet/Modules/Vote/Governance/GovernanceSelectTracks/ViewModel/GovernanceTrackViewModelFactory.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendumTrackGroup.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendumTrackType.swift

Support unknown tracks in the delegate & notification flow

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/ChainRegistry/Account/MetaAccountModel.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupMetadataManaging.swift
novawallet/Common/Services/CloudBackup/Operations/CloudBackupUpdateCalculationFactory.swift
novawallet/Modules/CloudBackup/CloudBackupCreate/EnableBackup/CloudBackupEnablePasswordInteractor.swift
novawallet/Modules/CloudBackup/CloudBackupCreate/EnableBackup/CloudBackupEnablePasswordWireframe.swift
novawallet/Modules/CloudBackup/CloudBackupCreate/NewBackup/CloudBackupCreateViewFactory.swift
novawallet/Modules/CloudBackup/CloudBackupSettings/CloudBackupSettingsInteractor.swift
novawallet/Modules/CloudBackup/CloudBackupSettings/CloudBackupSettingsPresenter.swift
novawallet/Modules/CloudBackup/CloudBackupSettings/CloudBackupSettingsProtocols.swift
novawallet/Modules/CloudBackup/CloudBackupSettings/CloudBackupSettingsWireframe.swift
novawallet/Modules/CloudBackup/CloudBackupSettings/ViewModel/CloudBackupSettingsViewModelFactory.swift
novawallet/Modules/ImportWallet/OptionsList/View/WalletImportOptionSecondaryView.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

- allow backup enable from settings with automatic redirection to the password setup screen
- fix crash on backup diff presentation
- fix glitch with multiline cell on import options screen

Enable backup from settings

---

Podfile
Podfile.lock
novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSyncService.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicOperationFactory.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicService.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicServiceFactory.swift
novawallet/Common/Substrate/Extension/AssetConversionTxPayment.swift
novawallet/Common/Substrate/Extension/AvailSignedExtension.swift
novawallet/Common/Substrate/Extension/ExtrinsicSignedExtensionFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppExtrinsicBuilderOperationFactory.swift
novawalletTests/Mocks/DataProviders/ExtrinsicServiceFactoryStub.swift

- update substrate sdk to support check metadata hash
- move application to the new refactored api for extensions

Support metadata hash

---

novawallet/Common/Substrate/Types/Xcm/V3/XcmV3Junction.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/BaseParaStakingRewardCalculatoService+Fetch.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/BaseParaStakingRewardCalculatoService.swift

- always load fresh total stake on parachain staking reward service init https://app.clickup.com/t/8694v0dnv
- fix asset hub swaps loading when there is unsupported asset

Fix parachain staking reward service & Asset Hub

---

novawallet/Common/Services/CloudBackup/Model/CloudBackupMetadataManaging.swift
novawallet/Modules/CloudBackup/CloudBackupImport/Base/BaseBackupEnterPasswordInteractor.swift
novawallet/Modules/CloudBackup/CloudBackupMessageSheet/CloudBackupMessageSheetViewFactory.swift
novawallet/Modules/CloudBackup/CloudBackupSettings/View/CloudBackupSettingsView.swift

- clear backup password on backup delete
- fix sync action cell layout on cloud backup settings screen
- fix bottom sheet height & remove unused bottom sheet

Fix layout issues & backup disable

---

novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Modules/NetworkManagement/NetworksList/NetworksListProtocols.swift
novawallet/Modules/NetworkManagement/NetworksList/NetworksListWireframe.swift

show wiki for "Integrate your own network" banner button

open web wiki url for custom networks banner button

---

novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkSetupFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractorError.swift
novawallet/Modules/NetworkManagement/KnownNetworksList/KnownNetworksListViewFactory.swift
novawallet/Modules/NetworkManagement/KnownNetworksList/KnownNetworksListWireframe.swift
novawallet/Modules/NetworkManagement/NetworksList/NetworksListWireframe.swift

- pass known network if routing from networks list;
- throw error if chain id obtain failed;
- map errors separately from interactor;
- remove old code

Routing and errors fixes for network management

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/ChainRegistry/LocalChain/ChainNodeModel.swift
novawallet/Common/Services/ChainRegistry/ChainRegistry.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionCreationParams.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionFactory.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionTLSSupportProvider.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionTransportFactory.swift
novawallet/Common/Services/WalletConnect/WalletConnectService.swift

- rollback transport protocol
- fix unsubscribe chains

Rollback websocket transport & fixes

---

novawallet/Common/Operation/NodePingOperationFactory.swift
novawallet/Common/Services/ChainRegistry/ChainFilterStrategy.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionPool.swift
novawallet/Common/ViewModel/EvmInputViewModel+Handler.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkSetupFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkViewFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkAddPresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkBasePresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkEditPresenter.swift
novawallet/Modules/NetworkManagement/KnownNetworksList/KnownNetworksListInteractor.swift
novawallet/Modules/NetworkManagement/NetworkDetails/NetworkDetailsInteractor.swift
novawallet/Modules/NetworkManagement/NetworkDetails/NetworkDetailsPresenter.swift
novawallet/Modules/NetworkManagement/NetworkNode/Presenter/NetworkNodeBasePresenter.swift

- iOS. Not able to add network or node name with spaces;
- iOS. After switch to another node switch remains enabled;
- iOS. add custom EVM network: block exporer not displayed;
- search case sensitivity;
- add type for EVM asset on custom network setup;
- node ping operation added condition for noSubstrateRuntime;
- ChainFilterStrategy fix transforms;
- default explorer creation;

fix bugs for network management

---

novawallet/Modules/NetworkManagement/NetworksList/NetworksListViewController.swift

Fixed using wrong index for networks section update on `NetworksListViewController`

find networks section index for update tableVIew

---

novawalletTests/Mocks/CommonMocks.swift
novawalletTests/Modules/Staking/StakingRewardDestinationSetup/StakingRewardDestinationSetupTests.swift

Add explicit fail with concrete error to determine the problem

Fix reward destination test

---

novawallet.xcodeproj/project.pbxproj
novawalletTests/Common/Helpers/ChainFilterStrategyTests.swift
novawalletTests/Helper/ChainModelGenerator.swift
novawalletTests/Mocks/CommonMocks.swift

added tests for ChainFilterStrategy

add tests for chain filter strategy

---

novawallet/Common/View/StackTable/StackAddressCell.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsPresenter.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsProtocols.swift
novawallet/Modules/Staking/StakingMain/Parachain/StakingParachainPresenter.swift
novawallet/Modules/Staking/StakingMain/Relaychain/StakingRelaychainPresenter.swift
novawallet/Modules/Staking/StakingMain/StakingMainPresenter.swift
novawallet/Modules/Staking/StakingMain/StakingMainProtocols.swift
novawallet/Modules/Staking/StakingMain/StakingMainViewController.swift

don't show account options on selected pool tap

Make Nomination Pool row non tapable in staking details

---

novawallet/Common/Extension/Foundation/TimeInterval+Localization.swift
novawallet/Modules/Vote/Governance/GovernanceUnlockSetup/GovernanceUnlockSetupPresenter.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendumStatusViewModelFactory.swift

Time format change from days to days hours

change time format for governance

---

novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Modules/Staking/Model/Relaychain/ElectedAndPrefValidators.swift
novawallet/Modules/Staking/Operations/ParachainStaking/ParaStkPreferredCollatorFactory.swift
novawallet/Modules/Staking/Operations/ValidatorOperationFactory/ValidatorOperationFactory+Protocol.swift
novawallet/Modules/Staking/Operations/ValidatorOperationFactory/ValidatorOperationFactoryProtocol.swift
novawallet/Modules/Staking/Parachain/ParaStkSelectCollators/ParaStkSelectCollatorsInteractor.swift
novawallet/Modules/Staking/Parachain/ParaStkSelectCollators/ParaStkSelectCollatorsPresenter.swift
novawallet/Modules/Staking/Parachain/ParaStkSelectCollators/ParaStkSelectCollatorsProtocols.swift
novawallet/Modules/Staking/SelectValidatorsFlow/SelectValidatorsStart/SelectValidatorsStartPresenter.swift
novawallet/Modules/Staking/Services/PreferredValidatorsProvider.swift
novawallet/Modules/Staking/StakingSetupAmount/Recommendation/DirectStakingRecommendationFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/StakingSetupAmountWireframe.swift
novawallet/Modules/Staking/StakingType/StakingTypePresenter.swift
novawalletTests/Mocks/DataProviders/ValidatorOperationFactoryStub.swift
novawalletTests/Mocks/ModuleMocks.swift
novawalletTests/Mocks/Staking/MockPreferredValidatorsProvider.swift
novawalletTests/Modules/Staking/SelectValidatorsFlow/StartSelectValidators/StartSelectValidatorsTests.swift

Excluded prohibited validators from recommended list

---

Podfile
Podfile.lock
novawallet/Common/Services/WalletConnect/WalletConnectMetadata.swift
novawallet/Common/Services/WalletConnect/WalletConnectService.swift
novawallet/Modules/AssetList/AssetListPresenter.swift
novawallet/Modules/DApp/WalletConnect/Model/WalletConnectMethod.swift
novawallet/Modules/DApp/WalletConnect/Model/WalletConnectModelFactory.swift
novawallet/Modules/DApp/WalletConnect/Model/WalletConnectSignModelFactory.swift
novawallet/Modules/DApp/WalletConnect/Protocols/WalletConnectErrorPresentable.swift
novawallet/Modules/DApp/WalletConnect/SessionDetails/WalletConnectSessionDetailsPresenter.swift
novawallet/Modules/DApp/WalletConnect/Sessions/WalletConnectSessionsPresenter.swift
novawallet/Modules/Settings/SettingsPresenter.swift

- upgrade Wallet Connect SDK to fix networking issues
- add support for eth_signTypedData_v4 (it is the same as eth_signTypedData)
- add error information when presenting wallet connect connection issue

Fix wallet connect

---

Podfile
Podfile.lock

Migrate to the novasama Starscream fork with version update

starscream version bump and migrate to novasama fork

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/Vote/Governance/Delegations/AddDelegation/AddDelegationViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/CommonDelegationTracks/CommonDelegationTracksViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateConfirm/GovernanceDelegateConfirmViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateInfo/GovernanceDelegateInfoViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateInfo/View/GovernanceDelegateInfoViewModelFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateSearch/GovernanceDelegateSearchViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateSetup/GovernanceDelegateSetupViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegateVotedReferenda/DelegateVotedReferendaViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationList/DelegationListViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/DelegationReferendumVoters/DelegationReferendumVotersViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/RevokeDelegationConfirm/GovernanceRevokeDelegationConfirmViewFactory.swift
novawallet/Modules/Vote/Governance/Delegations/YourDelegations/GovernanceYourDelegationsViewFactory.swift
novawallet/Modules/Vote/Governance/Operation/Fetch/OffchainVoting/GovernanceTotalVotesFactory.swift
novawallet/Modules/Vote/Governance/Operation/Fetch/OffchainVoting/SubqueryVotingResponse.swift
novawallet/Modules/Vote/Governance/ReferendumDetails/ReferendumDetailsPresenter.swift
novawallet/Modules/Vote/Governance/ReferendumDetails/ReferendumDetailsViewFactory.swift
novawallet/Modules/Vote/Governance/ReferendumDetails/View/ReferendumVotingStatusDetailsView.swift
novawallet/Modules/Vote/Governance/ReferendumVoteConfirm/ReferendumVoteConfirmViewFactory.swift
novawallet/Modules/Vote/Governance/ReferendumVoteSetup/ReferendumVoteSetupViewFactory.swift
novawallet/Modules/Vote/Governance/ReferendumVoters/ReferendumOnChainVotersViewFactory.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendmVotesViewModelFactory.swift
novawallet/Modules/Vote/Governance/ViewModel/ReferendumDisplayStringFactory.swift
novawallet/Modules/Vote/Parent/VoteChildPresenterFactory.swift

- Fixed offchain abstain and standard voting results mapping
- Refactor to split the logic between Gov1 and OpenGov

fix abstain and standard voting responses mapping

---

Podfile
Podfile.lock

switch starscream to fix branch

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicOperationFactory.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraExtrinsicConverter.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraExtrinsicOperationFactory.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraFeeService.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraFlowState.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraSwapExtrinsicService.swift

Use the new extrinsic service logic for the hydration swap flow

use new extrinsic logic for hydration swaps

---

novawallet/Modules/Transfer/TransferSetup/CrossChain/CrossChainTransferSetupPresenter.swift
novawallet/Modules/Transfer/TransferSetup/OnChain/OnChainTransferSetupPresenter.swift
novawallet/Modules/Transfer/TransferSetup/TransferSetupPresenter.swift
novawallet/Modules/Transfer/TransferSetup/TransferSetupProtocols.swift

Switch fee asset from the utility asset if needed

Switch fee asset from the utility asset if needed

---

novawallet/Common/Extension/Foundation/Predicate/NSPredicate+Transaction.swift

Revise predicates for history items to account for the new custom fees mechanics

Utility asset transaction history fix

---

novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/Hydra/HydraExtrinsicFeeInstaller.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraExtrinsicConverter.swift

Set batch type depending on referral call presence

Fix extrinsic batch type for hydration

---

novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/ExtrinsicFeeEstimationRegistry.swift
novawallet/Modules/Transfer/TransferSetup/OnChain/OnChainTransferSetupPresenter.swift

- return native fee estimator and installer if asset is utility
- check 'feeAssetChangeAvailable' and 'senderSendingAssetBalance' when switching fee chain asset automatically

fee estimation hot fixes

---

novawallet/es.lproj/Localizable.strings
novawallet/fr.lproj/Localizable.strings
novawallet/id.lproj/Localizable.strings
novawallet/it.lproj/Localizable.strings
novawallet/ja.lproj/Localizable.strings
novawallet/ko.lproj/Localizable.strings
novawallet/pl.lproj/Localizable.strings
novawallet/pt-PT.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings
novawallet/tr.lproj/Localizable.strings
novawallet/vi.lproj/Localizable.strings
novawallet/zh-Hans.lproj/Localizable.strings

fix: update localisation strings

---

NovaPushNotificationServiceExtension/Info.plist
novawallet/Common/Protocols/BaseErrorPresentable.swift
novawallet/Info.plist
novawallet/Modules/Vote/Governance/Validating/DataValidationRunner+GovVote.swift
novawallet/Modules/Vote/Governance/Validating/GovernanceErrorPresentable.swift
novawallet/Modules/Vote/Governance/Validating/GovernanceValidatorFactory.swift

Take into account ```fee.currentAccountAmount``` maybe nil when voting from proxy. In general we just reuse validations from regular gov voting that already takes proxy into account

Fix swipe gov proxy support

---

novawallet/Modules/Settings/ViewModel/SettingsViewModelFactory.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Elevate support section and reorder rows in Settings

---

novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkAddInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkSetupFinishStrategy.swift
novawallet/Modules/NetworkManagement/NetworkDetails/NetworkDetailsViewModelFactory.swift

- Add full preconfigured networks with changes by user
- Add `CustomNetworkModifyStrategy` to fix wrong modify behavior
- Show remote nodes for preconfigured networks

Network management fixes

---

novawallet/Modules/Vote/Governance/ReferendumDetails/ReferendumDetailsPresenter.swift
novawallet/Modules/Vote/Governance/ReferendumDetails/ReferendumDetailsProtocols.swift
novawallet/Modules/Vote/Governance/Referendums/Presenter/ReferendumsPresenter+ReferendumSections.swift
novawallet/Modules/Vote/Governance/Referendums/Presenter/ReferendumsPresenter.swift
novawallet/Modules/Vote/Governance/Referendums/ReferendumsProtocols.swift
novawallet/Modules/Vote/Governance/Referendums/ReferendumsWireframe.swift
novawallet/Modules/Vote/Parent/VoteChildPresenterFactory.swift

Use common account validation logic on SwipeGov banner tap.

validate has chain account for swipe gov banner

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/ParachainStakingLocalSubscriptionFactory.swift
novawallet/Common/Services/RemoteSubscription/Substrate/ParachainStakingRemoteSubscriptionService.swift
novawallet/Common/Substrate/Types/ParachainStaking/ParachainStaking+Types.swift
novawallet/Common/Substrate/Types/ParachainStaking/StorageCodingPath+ParachainStaking.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/BaseParaStakingRewardCalculatoService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/ParaStakingInflationDistributionProvider.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/ParaStakingRewardCalculatorEngine.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/TuringRewardCalculatorService.swift

Added `ParaStakingInflationDistrProvider` to decide and subscribe for supported storage that provides percentage for the parachain inflation distribution based on the runtime

Fix Moonriver breaking change

---

novawallet/Modules/Vote/Governance/ViewModel/ReferendumTrackType.swift

Fix Referendum agenda asset icon appearance

---

novawallet/Modules/AssetList/Models/Helpers/AssetListModelHelpers+Sorting.swift

Fix assets in asset list by 
total value > total amount > default

asset list asset sorting fix

---

novawallet/Modules/AssetList/AssetListViewController.swift
novawallet/Modules/AssetList/View/FlowLayout/AssetListFlowLayout.swift

Collapse section if expandable state changes to false.

update expanded state on layout update

---

Podfile
Podfile.lock
novawallet.xcodeproj/project.pbxproj
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/PolkadotRewardEngine.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/PolkadotRewardParamsService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorEngineFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorParamsService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/RewardCalculatorParamsServiceFactory.swift

Implement new APY calculation logic based on Polkadot runtime api

Support runtime api for predicting inflation

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/View/StackTable/StackTableView.swift
novawallet/Modules/AssetExchange/Common/AssetExchangeOperationFee.swift
novawallet/Modules/Swaps/Confirm/SwapConfirmPresenter.swift
novawallet/Modules/Swaps/Confirm/SwapConfirmProtocols.swift
novawallet/Modules/Swaps/Confirm/SwapConfirmWireframe.swift
novawallet/Modules/Swaps/Execution/SwapExecutionPresenter.swift
novawallet/Modules/Swaps/Execution/SwapExecutionProtocols.swift
novawallet/Modules/Swaps/Execution/SwapExecutionWireframe.swift
novawallet/Modules/Swaps/FeeDetails/SwapFeeDetailsPresenter.swift
novawallet/Modules/Swaps/FeeDetails/SwapFeeDetailsProtocols.swift
novawallet/Modules/Swaps/FeeDetails/SwapFeeDetailsViewController.swift
novawallet/Modules/Swaps/FeeDetails/SwapFeeDetailsViewFactory.swift
novawallet/Modules/Swaps/FeeDetails/SwapFeeDetailsViewLayout.swift
novawallet/Modules/Swaps/FeeDetails/View/SwapOperationFeeView.swift
novawallet/Modules/Swaps/FeeDetails/ViewModel/SwapFeeDetailsViewModel.swift
novawallet/Modules/Swaps/FeeDetails/ViewModel/SwapFeeDetailsViewModelFactory.swift
novawallet/Modules/Swaps/RouteDetails/SwapRouteDetailsInteractor.swift
novawallet/Modules/Swaps/RouteDetails/SwapRouteDetailsPresenter.swift
novawallet/Modules/Swaps/RouteDetails/SwapRouteDetailsProtocols.swift
novawallet/Modules/Swaps/RouteDetails/SwapRouteDetailsWireframe.swift
novawallet/Modules/Swaps/RouteDetails/ViewModel/SwapRouteDetailsViewModelFactory.swift
novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift
novawallet/Modules/Swaps/Setup/SwapSetupProtocols.swift
novawallet/Modules/Swaps/Setup/SwapSetupWireframe.swift

Fee details

---

novawallet/Modules/AssetsSearch/Model/SpendAssetSearchBuilder.swift

Enable zero balances for swaps

---

novawallet/Modules/AssetList/View/AssetListCardCell.swift
novawallet/Modules/PayCard/PayCardInteractor.swift
novawallet/en.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings

Renamed entry point for Nova Card

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/TokenDepositEventMatching/NativeTokenDepositedEventMatcher.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/TokenDepositEventMatching/NativeTokenMintedEventMatcher.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/TokenDepositEventMatching/TokenDepositEventMatcherFactory.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/TokenDepositEventMatching/TokenDepositEventMatching.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmDepositMonitoringService.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTokensArrivalDetector.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmViewFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppSignBytesConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppMessageSignFactory.swift

For Bifrost blockchain `Balances.Deposited` event is emitted when tokens are added to the account. This PR adds its support and checks for it if `Balances.Mint` event is not found.

Fix bifrost xcm detection

---

.github/workflows/codecov.yml
.github/workflows/deploy_staging.yml
.github/workflows/pull_request.yml
.github/workflows/push_develop.yml
novawalletTests/Modules/DApps/DAppOperationConfirm/DAppOperationConfirmTests.swift

Fix problem - https://github.com/maxim-lobanov/setup-xcode/issues/90
temporary set xcode version to 16.1

fix xcode install

---

novawallet/es.lproj/Localizable.strings
novawallet/fr.lproj/Localizable.strings
novawallet/hu.lproj/Localizable.strings
novawallet/id.lproj/Localizable.strings
novawallet/it.lproj/Localizable.strings
novawallet/ja.lproj/Localizable.strings
novawallet/ko.lproj/Localizable.strings
novawallet/pl.lproj/Localizable.strings
novawallet/pt-PT.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings
novawallet/tr.lproj/Localizable.strings
novawallet/vi.lproj/Localizable.strings
novawallet/zh-Hans.lproj/Localizable.strings

sdapp-localisation

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/ViewController/ModalCard/ModalCardPresentationConfiguration.swift
novawallet/Common/ViewController/ModalCard/ModalCardPresentationController.swift
novawallet/Common/ViewController/ModalCard/ModalCardPresentationFactory.swift
novawallet/Common/ViewController/ModalCard/ModalCardPresentationTransformFactory.swift
novawallet/Modules/AssetList/View/FlowLayout/AssetListFlowLayout.swift
novawallet/Modules/AssetList/View/FlowLayout/AssetListMeasurement.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserInteractor.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserViewFactory.swift
novawallet/Modules/DApp/DAppList/DAppListViewFactory.swift
novawallet/Modules/DApp/DAppList/ViewModel/DAppListViewModelFactory/DAppListViewModelFactory.swift
novawallet/Modules/MainTabBar/MainTabBarViewFactory.swift
novawallet/Modules/NovaMainAppContainer/NovaMainAppContainerViewController.swift

Fixed warnings around DAppBrowser, ModalCardPresentation and few factories

Fix warnings

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/Multistaking/Multistaking+Model.swift
novawallet/Common/Services/Multistaking/Multistaking+Mythos.swift
novawallet/Common/Services/Multistaking/MultistakingRepositoryFactory.swift
novawallet/Common/Services/Multistaking/MultistakingServices.swift
novawallet/Common/Services/Multistaking/MultistakingSyncService.swift
novawallet/Common/Services/Multistaking/MythosMultistakingUpdateService.swift
novawallet/Common/Storage/EntityToModel/StakingDashboardMythosMapper.swift
novawallet/Common/Substrate/Types/BalancesPallet/BalancesPallet+Freezes.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStaking+StoragePath.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStakingPallet+Freezes.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStakingPallet.swift
novawallet/Modules/Staking/Dashboard/ViewModel/StakingDashboardViewModelFactory.swift
novawallet/Modules/Staking/Model/ConsesusType.swift
novawallet/Modules/Staking/Model/StakingType.swift
novawallet/Modules/Staking/StakingMain/StakingMainPresenterFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/Model/StakingTypeBalanceFactory.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoViewFactory.swift

- add Mythos staking type
- add Mythos sync service to update the staking state on the dashboard
##

Mythos staking on the Dashboard

---

novawallet/Common/ViewController/ModalCard/ModalCardPresentationController.swift

Check inner UIScrollView and it's subclasses for being a descendant of another UIScrollView.

Fix UITextView scroll issues for card presentation

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/URLHandling/Parsing/OpenDAppUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenScreenUrlParsingServiceFactory.swift
novawallet/Common/URLHandling/ScreenOpenService.swift
novawallet/Modules/DApp/DAppList/DAppListNavigationTaskFactory/DAppListNavigationTaskFactory.swift
novawallet/Modules/DApp/DAppList/DAppListPresenter.swift
novawallet/Modules/DApp/DAppList/DAppListProtocols.swift
novawallet/Modules/DApp/DAppList/DAppListViewController.swift
novawallet/Modules/DApp/Model/DAppNavigation.swift
novawallet/Modules/MainTabBar/MainTabBarWireframe.swift

- Introduced `DAppNavigation` model to provide concrete DApp's url to open
- Separated DApp list view logic from navigation logic by introducing `DAppOpenViewProtocol`
- As we now can delay DApp's presentation with a task in `DAppListPresenter` removed not needed logic from url handling service

[CU-8697r1pmv] Allow open concrete dapp's page from app link

---

novawallet/Common/Helpers/PseudoRandomNumberGenerator.swift
novawallet/Modules/DApp/DAppList/ViewModel/DAppListViewModelFactory/DAppListViewModelFactory.swift

Use SplitMix64 pseudo-random seeded generator to sort dapps in deterministic way.

Fix dapp categories sorting

---

novawallet/Common/Services/WalletConnect/WalletConnectService.swift

Current logic in the `WalletConnectService` disconnects from the socket when viability flag is false but not reconnects to it when flag becomes true. That might be an issue when a user switches between wifi and lte or for some other reasons when flag changes while using the app. The PRs fixes the problem by allowing reconnection only in case socket is currently disconnected.

Fix wc signing

---

novawallet/en.lproj/Localizable.strings
novawallet/es.lproj/Localizable.strings
novawallet/fr.lproj/Localizable.strings
novawallet/hu.lproj/Localizable.strings
novawallet/id.lproj/Localizable.strings
novawallet/it.lproj/Localizable.strings
novawallet/ja.lproj/Localizable.strings
novawallet/ko.lproj/Localizable.strings
novawallet/pl.lproj/Localizable.strings
novawallet/pt-PT.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings
novawallet/tr.lproj/Localizable.strings
novawallet/vi.lproj/Localizable.strings
novawallet/zh-Hans.lproj/Localizable.strings

add popular localisation

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/MythosStakingLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/Subscription/DecodedProviderTypes.swift
novawallet/Common/DataProvider/Subscription/MythosStakingLocalStorageHandler.swift
novawallet/Common/DataProvider/Subscription/MythosStakingLocalStorageSubscriber.swift
novawallet/Common/Model/SubstrateAlias.swift
novawallet/Common/Services/RemoteSubscription/Substrate/MythosStakingRemoteSubscriptionService.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStaking+StoragePath.swift
novawallet/Modules/Staking/CollatorStaking/Services/CollatorStakingRewardCalculatorServiceProtocol.swift
novawallet/Modules/Staking/CollatorStaking/Services/CollatorStakingRewardService.swift
novawallet/Modules/Staking/Model/StakingSharedState/StakingSharedStateFactory.swift
novawallet/Modules/Staking/Mythos/Services/MythosStakingServiceFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/MythosStaking/MythosRewardCalculatorEngine.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/MythosStaking/MythosRewardCalculatorService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/BaseParaStakingRewardCalculatoService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/ParaStakingRewardCalculatorEngine.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/TuringRewardCalculatorService.swift
novawallet/Modules/Staking/StartStakingInfo/MythosStaking/StartStakingInfoMythosInteractor.swift
novawallet/Modules/Staking/StartStakingInfo/MythosStaking/StartStakingInfoMythosPresenter.swift
novawallet/Modules/Staking/StartStakingInfo/MythosStaking/StartStakingInfoMythosProtocols.swift
novawalletIntegrationTests/ParaStakingRewardCalculatorTests.swift

The PR implements reward calculation service for Mythos Staking. It also includes refactoring that adds base collator staking reward service. The collator reward service is then being reused for Mythos and Parachain staking
##

Mythos APR implementation

---

novawallet/Common/Extension/Foundation/TimeInterval+Localization.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStaking+StoragePath.swift
novawallet/Modules/Staking/Operations/MythosStaking/MythosCollatorOperationFactory.swift
novawallet/Modules/Staking/Services/EraValidatorsService/MythosStaking/MythosCollatorService.swift
novawallet/Modules/Staking/Services/EraValidatorsService/MythosStaking/MythosSessionCollators.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/MythosStaking/MythosRewardCalculatorEngine.swift
novawallet/Modules/Staking/StartStakingInfo/MythosStaking/StartStakingInfoMythosPresenter.swift
novawallet/Modules/Staking/StartStakingInfo/ParachainStaking/StartStakingInfoParachainPresenter.swift

- APR calculation must account only non invurnerable collators
- Add option to display min number of minutes for time
- Remove restriction for updates on Start Staking based on block numbers

Fix apr calc and more

---

novawallet/Modules/Banners/BannersPresenter.swift
novawallet/Modules/Banners/BannersProtocols.swift
novawallet/Modules/DApp/DAppList/DAppListPresenter.swift

This PR adds locale getter to `Banners` module so parent modules can check it and update if needed.

Update banners locale on DAppList module setup

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/AssetDetails/AssetDetailsViewController.swift
novawallet/Modules/AssetDetails/View/AssetDetailsBalanceWidget.swift
novawallet/Modules/AssetDetails/View/AssetDetailsViewLayout.swift
novawallet/Modules/AssetDetails/View/StackTitleValueIconView.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartDataSource.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartPresenter.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartProtocols.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartViewController.swift
novawallet/Modules/AssetPriceChart/Factory/AssetPriceChartViewModelFactory.swift
novawallet/Modules/AssetPriceChart/Model/AssetPriceChartWidgetViewModel.swift

This PR adds logic for updating current displayed price when user interacts with chart.

update price according to selected entry

---

novawallet/Modules/Staking/StakingMain/Mythos/ViewModel/MythosStakingStateViewModelFactory.swift

- display loading state if no collators loaded

Improve details state loading

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/MythosStakingLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/SubstrateLocalSubscriptionFactory.swift
novawallet/Common/EventCenter/EventVisitor.swift
novawallet/Common/EventCenter/Events/StakingRewardInfoChanged.swift
novawallet/Modules/Staking/CollatorStaking/Services/CollatorStakingRewardService.swift
novawallet/Modules/Staking/Mythos/Services/MythosStakingServiceFactory.swift
novawallet/Modules/Staking/Services/ParachainStakingServiceFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/MythosStaking/MythosRewardCalculatorService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/BaseParaStakingRewardCalculatoService.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/Parachain/TuringRewardCalculatorService.swift
novawallet/Modules/Staking/StartStakingInfo/MythosStaking/StartStakingInfoMythosInteractor.swift
novawallet/Modules/Staking/StartStakingInfo/MythosStaking/StartStakingInfoMythosPresenter.swift
novawalletIntegrationTests/ParaStakingRewardCalculatorTests.swift

- use default value for ExtraRewards storage when its empty
- add staking info change event to the event center and integrate into Mythos staking

Improve Mythos APY calculation

---

novawallet/Common/ViewModel/WalletSwitchViewModel.swift
novawallet/Common/ViewModel/WalletSwitchViewModelFactory.swift
novawallet/Modules/AssetList/AssetListPresenter.swift
novawallet/Modules/AssetList/ViewModel/AssetListViewModelFactory.swift
novawallet/Modules/DApp/DAppBrowser/StateMachine/DAppBrowserStateDataSource.swift
novawallet/Modules/DApp/DAppList/ViewModel/DAppListViewModelFactory/DAppListViewModelFactory.swift
novawallet/Modules/Settings/SettingsViewController.swift
novawallet/Modules/Settings/ViewModel/SettingsAccountViewModel.swift
novawallet/Modules/Settings/ViewModel/SettingsViewModelFactory.swift
novawallet/Modules/Staking/Dashboard/StakingDashboardPresenter.swift
novawallet/Modules/Vote/Parent/VotePresenter.swift

- add support for evm addresses when connecting via Polkado JS extension protocol
- fix wallet switch icon on DApp browser screen

Support ethereum in the Browser & fixes

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/PayCard/Model/PayCardStatus.swift
novawallet/Modules/PayCard/PayCardInteractor.swift
novawallet/Modules/PayCard/PayCardPresenter.swift
novawallet/Modules/PayCard/PayCardProtocols.swift
novawallet/Modules/PayCard/PayCardWireframe.swift
novawallet/Modules/PayCard/View/PayCardSheetMode.swift
novawallet/Modules/PayCard/View/PayCardSheetViewFactory.swift
novawallet/en.lproj/Localizable.strings
novawallet/es.lproj/Localizable.strings
novawallet/fr.lproj/Localizable.strings
novawallet/hu.lproj/Localizable.strings
novawallet/id.lproj/Localizable.strings
novawallet/it.lproj/Localizable.strings
novawallet/ja.lproj/Localizable.strings
novawallet/ko.lproj/Localizable.strings
novawallet/pl.lproj/Localizable.strings
novawallet/pt-PT.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings
novawallet/tr.lproj/Localizable.strings
novawallet/vi.lproj/Localizable.strings
novawallet/zh-Hans.lproj/Localizable.strings

- show "You card is being funded" bottom sheet in case of topup

Add topup bottom sheet

---

novawallet/Modules/DApp/DAppBrowser/DAppBrowserInteractor.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserPresenter.swift
novawallet/Modules/DApp/DAppBrowser/Tabs/DAppBrowserTabManager/DAppBrowserTabManager.swift
novawallet/Modules/DApp/DAppBrowser/Transports/DAppMetamaskTransport.swift
novawallet/Modules/DApp/DAppBrowser/Transports/DAppPolkadotExtensionTransport.swift

This PR fixes dApp state restoration after browser minimize/maximize action or switching tabs.

Fix dApp state restoration

---

novawallet/Modules/DApp/DAppBrowser/DAppBrowserWidget/DAppBrowserWidgetWireframe.swift

This PR adds logic that cleans browser's navigation stack when on minimize action.

DAppBrowser navigation stack fix

---

novawallet/Common/Model/StatemineAsset/StatemineAssetSerializer.swift
novawallet/Common/Services/AssetConversion/AssetHub/AssetHubTokensConverter.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppEthereumConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppEthereumSignBytesInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Proccessing.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Protocol.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmPresenter.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmViewFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppSignBytesConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppExtrinsicBuilderOperationFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppOperationConfirmModel.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppOperationProcessedResult.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppParsedExtrinsic.swift
novawallet/Modules/DApp/DAppOperationConfirm/ViewModel/DAppOperationConfirmViewModelFactory.swift
novawallet/Modules/DApp/Model/PolkadotExtensionProtocol/PolkadotExtensionExtrinsic.swift

- allow fee in custom asset using `assetId` field for DApp browser

Feature asset id dapp

---

novawallet/es.lproj/Localizable.strings
novawallet/fr.lproj/Localizable.strings
novawallet/hu.lproj/Localizable.strings
novawallet/id.lproj/Localizable.strings
novawallet/it.lproj/Localizable.strings
novawallet/ja.lproj/Localizable.strings
novawallet/ko.lproj/Localizable.strings
novawallet/pl.lproj/Localizable.strings
novawallet/pt-PT.lproj/Localizable.strings
novawallet/ru.lproj/Localizable.strings
novawallet/tr.lproj/Localizable.strings
novawallet/vi.lproj/Localizable.strings
novawallet/zh-Hans.lproj/Localizable.strings

add localised strings

---

novawallet/Modules/Staking/NominationPools/Unstake/Operation/NominationPoolsUnstakeOperationFactory.swift
novawallet/Modules/Staking/Validation/StakingBaseDataValidatingFactory.swift

- fix circular reference for staking modules that use validations
- fix unstaking duration fetch for nomination pools limits validation

Fix staking issues

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Migration/SubstrateStorageVersion.swift
novawallet/Common/Model/ChainRegistry/LocalChain/AssetModel+Remote.swift
novawallet/Common/Model/ChainRegistry/LocalChain/AssetModel.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteAssetModel+Evm.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteAssetModel.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteEvmToken.swift
novawallet/Common/RampProvider/Providers/MercuryoProvider.swift
novawallet/Common/RampProvider/Providers/TransakProvider.swift
novawallet/Common/Storage/EntityToModel/ChainModelMapper.swift
novawallet/Common/Storage/SubstrateDataModel.xcdatamodeld/.xccurrentversion
novawallet/Common/Storage/SubstrateDataModel.xcdatamodeld/SubstrateDataModel37.xcdatamodel/contents
novawallet/Common/Storage/SubstrateDataStorageFacade.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkSetupFactory.swift
novawallet/Modules/TokensManage/Model/AssetModel+TokenAddRequest.swift
novawalletTests/Helper/ChainModelGenerator.swift
novawalletTests/Modules/Wallet/PurchaseProviders/WalletPurchaseProvidersTests.swift

This PR adds sell providers with persistence support to asset model

Sell providers persistence

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/UIKit/Style/UILabel+Style.swift
novawallet/Common/RampProvider/Providers/BanxaProvider.swift
novawallet/Common/RampProvider/Providers/MercuryoProvider.swift
novawallet/Common/RampProvider/Providers/TransakProvider.swift
novawallet/Common/RampProvider/RampProviderProtocol.swift
novawallet/Modules/SelectRampProvider/Factory/SelectRampProviderViewModelFactory.swift
novawallet/Modules/SelectRampProvider/Model/FiatPaymentMethodViewModel.swift
novawallet/Modules/SelectRampProvider/Model/SelectRampProviderViewModel.swift
novawallet/Modules/SelectRampProvider/View/RampProviderView.swift

This PR moves payment methods to model and adds other payment methods counter for UI.

Ramp payment methods refactor

---

novawallet/Common/Services/DelegatedAccounts/Repositories/DelegatedAccountsRepository.swift
novawallet/Common/Services/DelegatedAccounts/Repositories/ProxyAccountsRepository.swift
novawallet/Common/Services/DelegatedAccounts/SyncService/DelegatedAccountChangesCalculator/DelegatedAccountsChangesCalculator.swift
novawallet/Common/Services/DelegatedAccounts/SyncService/DelegatedAccountChangesCalculator/DelegatedMetaAccountFactory/DelegatedMetaAccountFactory.swift
novawallet/Common/Services/DelegatedAccounts/SyncService/DelegatedAccountChangesCalculator/DelegatedMetaAccountFactory/MultisigMetaAccountFactory.swift
novawallet/Common/Services/DelegatedAccounts/SyncService/DelegatedAccountChangesCalculator/DelegatedMetaAccountFactory/ProxyMetaAccountFactory.swift

This PR corrects mapping and fetching logic for nested proxies and multisigs.

Correct mapping for nested proxies and multisigs

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Helpers/CustomAssetMapper.swift
novawallet/Common/Model/AssetStorageInfo.swift
novawallet/Common/Model/ChainRegistry/LocalChain/AssetModel.swift
novawallet/Common/Model/ChainRegistry/LocalChain/AssetTypeExtras.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteAssetModel+Evm.swift
novawallet/Common/Model/Evm/ChainModel+Evm.swift
novawallet/Modules/TokensManage/Model/AssetModel+TokenAddRequest.swift
novawallet/Modules/TransactionHistory/Service/AssetHistoryFactoryFacade.swift
novawallet/Modules/Transfer/BaseTransfer/OnChain/EvmOnChainTransferInteractor.swift

The PR adds support for evm asset type in chain.json. It also maintains backward compatibility with erc20 assets added by a user.

Xcm with erc20

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/Subscription/Multisig/MultisigListLocalStorageSubscriber.swift
novawallet/Common/DataProvider/Subscription/Multisig/MultisigListLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/Subscription/Multisig/MultisigListLocalSubscriptionHandler.swift
novawallet/Common/Model/ChainRegistry/Account/DelegatedAccount+ProxyAccountModel.swift
novawallet/Common/Services/DelegatedAccounts/WalletNotificationService.swift
novawallet/Common/Services/ServiceCoordinator.swift
novawallet/Common/Storage/EntityToModel/MultisigAccountMapper.swift
novawalletTests/Mocks/ModuleMocks.swift
novawalletTests/Modules/DApps/DAppList/DAppListTests.swift
novawalletTests/Modules/Settings/SettingsTests.swift

The PR introduces local subscription implementation for multisigs and extends `WalletNotificationService` to handle multisig updates.

Add multisig local subscription for multisigs

---

novawallet/Modules/DelegatedAccounts/DelegatedAccountsUpdate/DelegatedAccountsUpdatePresenter.swift

The PR fixes accounts counting logic when calculating preferred content size.

[8699c1gzc] Discovery bottom sheet info can be not shown

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/Factory/MultisigOperationConfirmViewFactory.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/Factory/MultisigOperationConfirmViewModelFactory.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperations/Model/MultisigOperationsFlowState.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperations/MultisigOperationsInteractor.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperations/MultisigOperationsPresenter.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperations/MultisigOperationsProtocols.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperations/MultisigOperationsWireframe.swift
novawallet/Modules/DelegatedAccounts/Multisig/PendingOperationProxy/MultisigPendingOperationProviderProxy.swift
novawallet/Modules/DelegatedAccounts/Multisig/PendingOperationProxy/MultisigProviderProxySnapshot.swift

[CU-8699pyt5d]
PR adds snapshotting interface for `MultisigOperationProviderProxy` state. The state is transferred further to reuse the same formatting cache.

Multisig operation cache transfer and flow state

---

novawallet.xcodeproj/project.pbxproj
novawallet/Modules/DApp/DAppBrowser/StateMachine/DAppBrowserSigningChainResolver.swift
novawalletTests/Modules/DApps/DAppBrowser/DAppBrowserSigningChainResolverTests.swift

message signing for Ethereum based parachains

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/AccountRepositoryFactory.swift
novawallet/Common/Migration/UserStorageVersion.swift
novawallet/Common/Model/ChainRegistry/Account/ProxiedSettings.swift
novawallet/Common/Storage/EntityToModel/ProxiedSettingsMapper.swift
novawallet/Common/Storage/UserDataModel.xcdatamodeld/.xccurrentversion
novawallet/Common/Storage/UserDataModel.xcdatamodeld/MultiassetUserDataModel16.xcdatamodel/contents
novawallet/Common/Storage/UserDataStorageFacade.swift
novawallet/Modules/DelegatedAccounts/DelegatedMessageSheet/DelegatedMessageSheetInteractor.swift
novawallet/Modules/DelegatedAccounts/DelegatedMessageSheet/DelegatedMessageSheetViewFactory.swift
novawallet/Modules/DelegatedAccounts/DelegatedSignConfirmation/DelegatedSignConfirmationInteractor.swift
novawallet/Modules/DelegatedAccounts/DelegatedSignConfirmation/DelegatedSignConfirmationViewFactory.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/Factory/MultisigOperationConfirmViewFactory.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/MultisigOperationConfirmInteractor.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/MultisigOperationConfirmPresenter.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/MultisigOperationConfirmProtocols.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/MultisigOperationConfirmWireframe.swift
novawallet/Modules/DelegatedAccounts/Multisig/MultisigOperationConfirm/Reject/MultisigOperationRejectInteractor.swift
novawalletTests/Common/Migration/StorageLocationMigrationTests.swift
novawalletTests/Mocks/CommonMocks.swift

The PR adds reject confirmation screen for multisig operations
https://github.com/user-attachments/assets/88001f2b-db89-45fb-99d2-33caa5c9285d

Add MS operation reject confirmation sheet

---

novawalletTests/Mocks/ModuleMocks.swift
novawalletTests/Modules/DApps/DAppBrowser/DAppBrowserTests.swift

The PR adds fixes for DApp Browser tests.

Fix DApp Browser tests

---

novawallet/Modules/Notifications/WalletList/WalletCheckboxTableViewCell.swift
novawallet/Modules/WalletsList/Manage/WalletManageTableViewCell.swift

The PR fixes compression rules for the wallet cell layout to prevent selection indicators to push right

fix compression rules

---

novawallet/Common/Services/AssetExchange/HydraExchange/AavePool/HydraAaveQuoteParamsService.swift

The PR fixes race condition due to lack of proper mutex protection in `HydraAaveParamsService`

Fix crash in HydraAaveParamsService

---

NovaPushNotificationServiceExtension/Handlers/Multisig/CommonMultisigHandler.swift

The PR fixes multisig notifications processing corner case when there is multisig's proxy added to Nova.

Fix multisig notifications corner case

---

.github/workflows/push_develop.yml

Distribution went [successfull](https://github.com/novasamatech/nova-wallet-ios/actions/runs/17789413544)

Fix develop CI
