novasamatech/nova-wallet-ios

.github/workflows/pull_request.yml

That PR changes trigger CI in order to run unit tests for each commit in pull-request

GitHub Actions. Change trigger for pull-request runner

---

novawallet/Common/Extension/Foundation/NSPredicate+Transaction.swift
novawallet/Modules/AssetDetails/AssetDetailsPresenter.swift

- take into account crowdloans and reserve when calculating total balance and locked balance #85ztqb4yd
- fix local history filter for asset details #85ztqb32z

Fix aseet details and locks

---

novawallet/Common/Model/ChainRegistry/LocalChain/ChainModel.swift
novawallet/Common/Network/Subquery/Models/SubqueryHistory.swift
novawallet/Common/Network/Subquery/SubqueryHistory+Wallet.swift
novawallet/Modules/OperationDetails/ViewModel/OperationDetailsViewModelFactory.swift
novawallet/Modules/Staking/Dashboard/Model/StakingDashboardBuilder.swift
novawallet/Modules/Staking/Dashboard/Model/StakingDashboardModel.swift
novawallet/Modules/Staking/Dashboard/ViewModel/StakingDashboardViewModelFactory.swift
novawallet/Modules/Staking/Operations/BlockTimeOperationFactory.swift
novawallet/Modules/Staking/StakingSetupAmount/Model/StakingTypeBalanceFactory.swift
novawallet/Modules/Staking/StartStakingInfo/Model/DefaultStakingRewardDestination.swift
novawallet/Modules/Staking/StartStakingInfo/Model/StartStakingStateProtocol.swift
novawallet/Modules/Staking/StartStakingInfo/Model/StartStakingViewModelFactory.swift
novawallet/Modules/Staking/StartStakingInfo/ParachainStaking/StartStakingInfoParachainPresenter.swift
novawallet/Modules/Staking/StartStakingInfo/RelaychainStaking/StartStakingInfoRelaychainPresenter.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoBasePresenter.swift
novawallet/Modules/Staking/StartStakingInfo/StartStakingInfoViewFactory.swift

- display the same available balance depending on staking type on Dashboard, Start Staking Info and Setup Amount #85ztugceh
- use default block time from chain #85ztrenv9
- display start staking info depending on selected staking type #85ztw2vtq

Improve start staking

---

novawallet/Modules/Swaps/Slippage/SwapSlippagePresenter.swift
novawallet/Modules/Swaps/Slippage/SwapSlippageProtocols.swift
novawallet/Modules/Swaps/Slippage/SwapSlippageViewController.swift

Bugs
- not possible to input decimals
- reset works only on input, saves applied slippage, maybe we can disable Apply button for already applied slippage
Done:
- Fix locale for input view model
- Add updating apply button state

Swaps: Slippage bugfixes

---

novawallet/Common/URLHandling/Parsing/OpenGovernanceUrlParsingService.swift
novawallet/Common/URLHandling/Parsing/OpenScreenUrlParsingService.swift

If type is not provided then
- opengov must be opened if the chain supports multiple types and opengov in the list
- the target gov must be opened if the chain supports the only gov type
- nothing must be opened if there are multiple gov types and a user must see a dialog with the problem

Bugfix: Open referendum details

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/SubstrateSdk/StorageKeyFactory+Implicit.swift
novawallet/Common/Migration/SubstrateStorageVersion.swift
novawallet/Common/Model/ChainRegistry/LocalChain/ChainModel.swift
novawallet/Common/Model/ChainRegistry/LocalChain/ChainSyncMode.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteChainModel.swift
novawallet/Common/Services/ChainRegistry/ChainModelConversion.swift
novawallet/Common/Services/ChainRegistry/ChainRegistry.swift
novawallet/Common/Services/ChainRegistry/ChainSyncModeUpdateService.swift
novawallet/Common/Services/ChainRegistry/ChainSyncService.swift
novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionPool.swift
novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimePolicyService.swift
novawallet/Common/Services/ChainRegistry/SpecVersionSubscriptionFactory.swift
novawallet/Common/Services/RemoteSubscription/Equilibrium/EquilibriumAssetBalanceUpdatingService.swift
novawallet/Common/Services/RemoteSubscription/Substrate/AccountInfoUpdatingService.swift
novawallet/Common/Services/RemoteSubscription/Substrate/AssetsUpdatingService.swift
novawallet/Common/Services/ServiceCoordinator.swift
novawallet/Common/Services/WebSocketService/StorageSubscription/ChainRemoteAccountDetector.swift
novawallet/Common/Services/WebSocketService/StorageSubscription/RawDataStorageSubscription.swift
novawallet/Common/Storage/EntityToModel/ChainModelMapper.swift
novawallet/Common/Storage/SubstrateDataModel.xcdatamodeld/.xccurrentversion
novawallet/Common/Storage/SubstrateDataModel.xcdatamodeld/SubstrateDataModel23.xcdatamodel/contents
novawallet/Common/Storage/SubstrateDataStorageFacade.swift
novawallet/Modules/TransactionHistory/LocalFilter/TransactionHistoryLocalFilterFactory.swift
novawallet/Modules/TransactionHistory/TransactionHistoryViewFactory.swift
novawalletTests/Common/Services/ChainRegistry/ChainRegistryTests.swift
novawalletTests/Helper/ChainModelGenerator.swift
novawalletTests/Mocks/CommonMocks.swift

Introduce disabled/light/full sync modes for chain: 
1) In disabled mode there is no connection or runtime created;
2) In light mode connection is created but no runtime. Also there is a class ChainSyncModeUpdateService running that monitors user's account info and in case it exists switches chain to the full sync mode;
3) In full mode both connection and runtime are created;
Add support for ```fullSyncByDefault``` option from remote config. It switches chain to full sync unless it is not disabled by the user (running in light mode).
Chain automatically switches to the full sync if it is running in light mode and some part of the code requested the runtime. The main idea here is that a chain doesn't consume resources if a user doesn't interact with it but when a user tries to make an …

Network state management

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/TokenOperation.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessing.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+Matching.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+SwapMatching.swift
novawallet/Common/Services/TransactionSubscription/NestedExtrinsicCallMapper.swift
novawallet/Modules/AssetDetails/AssetDetailsPresenter.swift
novawallet/Modules/OperationDetails/OperationDataProviders/OperationDetailsDataProviderFactory.swift
novawallet/Modules/OperationDetails/OperationDataProviders/OperationDetailsDirectStakingProvider.swift
novawallet/Modules/OperationDetails/OperationDataProviders/OperationDetailsPoolStakingProvider.swift
novawallet/Modules/OperationDetails/OperationDataProviders/OperationDetailsTransferProvider.swift
novawallet/Modules/TransactionHistory/Model/TransactionHistoryViewModelFactory.swift

The implementation idea is to use NestedExtrinsicCallMapper to recursively traverse the call and derive target call and call's sender. Call's sender is an account that is the origin for the call. Call sender differs from extrinsic sender only for proxies currently.

Support realtime history updates for proxies 8693b5ayg

---

novawallet/Common/Operation/OperationCombiningService.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicSplitter.swift
novawallet/Common/Substrate/Types/Preimage/Preimage.swift
novawallet/Modules/Vote/Governance/Operation/Action/Gov2ActionOperationFactory.swift

- prefer RequestStatusFor to fetch preimage status of the call
- use 0.6 coefficient to address transaction acceptance issue for gov calls

Prepare for Kusama runtime upgrade

---

novawallet/Common/Substrate/Types/Treasury/Treasury+Calls.swift
novawallet/Modules/Vote/Governance/Operation/Action/Parser/GovTreasurySpentAmountHandler.swift

New Kusama runtime introduce spend via xcm option and previously call to spend assets local has been renamed to spend_local. We now need to support both old version of spend and spend_local.
Note: we don't currently support new version that spends something via xcm in this PR

Support spend local

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/BigRational.swift
novawallet/Common/Model/ChainRegistry/LocalChain/ChainModelFetchError.swift
novawallet/Common/Model/KnownChainIds.swift
novawallet/Common/Operation/StorageDecodingOperation+Init.swift
novawallet/Common/Operation/StorageKeysOperationFactory.swift
novawallet/Common/Substrate/Types/HydraDx/HydraDx+Constants.swift
novawallet/Common/Substrate/Types/HydraDx/HydraDx+Storages.swift
novawallet/Common/Substrate/Types/HydraDx/HydraDx.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraDxTokenConverter.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraOmnipoolOperationFactory.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraOmnipoolQuoteRemoteState.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraOmnipoolQuoteService.swift
novawalletIntegrationTests/HydraDxSwapTests.swift

Implementation details:
- omnipool pallet is used for swaps, it assumes that any token can be traded with other via special hub token. We don't want a user to swap the hub token - it must be manually filtered out.
- we are using subscription for onchain parameters to calculate the quote. For this purpose ```HydraOmnipoolQuoteService``` is introduced and cached in the operation factory. Later interactor can track the state of the service and initiate quote recalculation without need to update it every block as we do for AssetHub swaps.
- quote is manually calculated because Hydra doesn't have rpc as we use for the Asset Hub. That's why we need to manually do the math in the ```calculateSellQuote``` and ```calculateBuyQuote``` functions.

Swap pair and quote calculation for Hydra swaps

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Configs/ApplicationConfigs.swift
novawallet/Common/Graphs/GraphModel.swift
novawallet/Common/Substrate/Types/HydraDx/HydraStableswap+Storages.swift
novawallet/Common/Substrate/Types/HydraDx/HydraStableswap.swift
novawallet/Modules/AssetConversion/Service/HydraDx/AssetConversionAggregationFactory+HydraDx.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraOmnipoolTokensFactory.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraStableswapPoolService.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraStableswapPoolState.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraStableswapsTokensFactory.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraTokensFactory.swift
novawalletIntegrationTests/HydraDxSwapTests.swift

The idea is to abstract further tokens operations factory. Now we have ```HydraTokensFactory``` that can fetch tokens from ```HydraOmnipoolOperationFactory``` and ```HydraStableswapOperationFactory``` and establish connections between them. This means that we can now have pairs represented by tokens from different pools (omnipool or stableswap).

Stableswaps tokens support

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/MaxCounter.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+AssetHubSwapMatching.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+HydraSwapMatching.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraFeeService.swift
novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift

- Currently HydraDX runtime has an issue that if fee is paid in custom asset then we need to leave at least ED in that custom asset otherwise extrinsic fails;
- Also introduced a counter to prevent quote -> fee -> quote ... -> fee ... deadlock when rate changes fast on the exchange;

Fix hydra swaps

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/NftLocalSubscriptionFactory.swift
novawallet/Common/Extension/Foundation/Predicate/NSPredicate+Filter.swift
novawallet/Common/Network/DistributedStorage/DistributedUrlParser.swift
novawallet/Common/Network/Files/FileDownloadOperation.swift
novawallet/Modules/AssetList/ViewModel/AssetListViewModelFactory.swift
novawallet/Modules/Nft/Model/NftType.swift
novawallet/Modules/Nft/NftDetails/KodaDotDetailsInteractor.swift
novawallet/Modules/Nft/NftDetails/NftDetailsInteractor.swift
novawallet/Modules/Nft/NftDetails/NftDetailsViewFactory.swift
novawallet/Modules/Nft/NftList/ViewModel/NftListViewModelFactory.swift
novawallet/Modules/Nft/Services/ChainModel+Nft.swift
novawallet/Modules/Nft/Services/KodaDot/KodaDotNft.swift
novawallet/Modules/Nft/Services/KodaDot/KodaDotNftModelConverter.swift
novawallet/Modules/Nft/Services/KodaDot/KodaDotNftOperationFactory.swift
novawallet/Modules/Nft/Services/KodaDot/KodaDotNftSyncService.swift
novawallet/Modules/Nft/Services/NFTClearService.swift
novawallet/Modules/Nft/Services/NftFileDownloadService.swift
novawallet/Modules/Nft/Services/Uniques/NftModel+Identifier.swift

- Add support of Kodadot NFTs from Kusama and Polkadot Asset Hubs: basically, from Uniques and NFT pallets
- As we had previously support for Uniques pallet on Kusama then there is no longer to sync/display such nfts as KodaDot now handles them. We now have NFTClearService to clear such excluded NFTs locally.

Kodadot Asset Hub NFT support

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/SettingsExtension.swift
novawallet/Common/Model/KeystoreTag.swift
novawallet/Common/Services/CloudBackup/CloudBackupServiceFacade.swift
novawallet/Common/Services/CloudBackup/CloudBackupServiceFacadeProtocol.swift
novawallet/Common/Services/CloudBackup/CloudBackupServiceFactory.swift
novawallet/Common/Services/CloudBackup/CloudBackupServiceFactoryProtocol.swift
novawallet/Common/Services/CloudBackup/CloudBackupSyncFacade.swift
novawallet/Common/Services/CloudBackup/CloudBackupSyncFactory.swift
novawallet/Common/Services/CloudBackup/CloudBackupSyncService.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupDiff+Helper.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupDiffing.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupFileModel.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupMetadataManaging.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupSyncState.swift
novawallet/Common/Services/CloudBackup/Model/NSPredicate+CloudBackup.swift
novawallet/Common/Services/CloudBackup/Monitor/CloudBackupUpdateMonitoring.swift
novawallet/Common/Services/CloudBackup/Monitor/ICloudBackupUpdateMonitor.swift
novawallet/Common/Services/CloudBackup/Operations/CloudBackupUpdateApplicationFactory.swift
novawallet/Common/Services/CloudBackup/Operations/CloudBackupUpdateCalculationFactory.swift
novawallet/Modules/CloudBackup/CloudBackupCreate/CloudBackupCreateInteractor.swift
novawalletIntegrationTests/CloudBackup/CloudBackupFacadeTests.swift

The aim of the PR is to define an architecture of how interactions will communicate with Cloud Backup syncing:
- ```CloudBackupSyncService``` maintains the state of the latest diff attempt between local wallets and remote wallets. It is automatically triggered when ```setup``` is called and ```syncUp``` can be called later on to trigger a new sync;
-  ```CloudBackupSyncServiceFacade``` offers an interface to enable/disable cloud backup and allows to subscribe to that state. Automatically, creates ```CloudBackupSyncService``` when backup is enabled and clears it when disabled. It creates a monitor to automatically detect new remote file and trigger sync up. And finally, one can use ```syncUp``` method to automatically trigger syncing, for example, when wallets changed locally.
- …

Cloud backup service orchestration

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/ChainRegistry/Account/MetaAccountModelType+ExtrinsicLimit.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicServiceTypes+Conversion.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicSplitter.swift
novawallet/Modules/Ledger/TxConfirmation/LedgerTxConfirmPresenter.swift
novawallet/Modules/Ledger/TxConfirmation/LedgerTxConfirmProtocols.swift
novawallet/Modules/Ledger/TxConfirmation/LedgerTxConfirmWireframe.swift
novawallet/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationInteractor.swift
novawallet/Modules/Vote/Governance/Delegations/Delegate/GovernanceDelegateInteractor.swift
novawallet/Modules/Vote/Governance/GovernanceRemoveVotesConfirm/GovernanceRemoveVotesConfirmInteractor.swift
novawallet/Modules/Vote/Governance/GovernanceRemoveVotesConfirm/GovernanceRemoveVotesConfirmPresenter.swift
novawallet/Modules/Vote/Governance/GovernanceRemoveVotesConfirm/GovernanceRemoveVotesConfirmProtocols.swift
novawallet/Modules/Vote/Governance/GovernanceRemoveVotesConfirm/GovernanceRemoveVotesConfirmViewFactory.swift
novawallet/Modules/Vote/Governance/GovernanceRemoveVotesConfirm/GovernanceRemoveVotesConfirmWireframe.swift
novawallet/Modules/Vote/Governance/GovernanceUnlockConfirm/GovernanceUnlockConfirmInteractor.swift
novawallet/Modules/Vote/Governance/GovernanceUnlockConfirm/GovernanceUnlockConfirmPresenter.swift
novawallet/Modules/Vote/Governance/GovernanceUnlockConfirm/GovernanceUnlockConfirmProtocols.swift
novawallet/Modules/Vote/Governance/GovernanceUnlockConfirm/GovernanceUnlockConfirmViewFactory.swift
novawallet/Modules/Vote/Governance/GovernanceUnlockConfirm/GovernanceUnlockConfirmWireframe.swift
novawallet/Modules/Vote/Governance/Operation/Extrinsics/Gov1ExtrinsicFactory.swift
novawallet/Modules/Vote/Governance/Operation/Extrinsics/Gov2ExtrinsicFactory.swift
novawallet/Modules/Vote/Governance/Operation/GovernanceExtrinsicFactoryProtocol.swift
novawalletTests/Common/Services/ChainRegistry/ChainRegistryTests.swift
novawalletTests/Modules/AccountConfirm/AccountConfirmTests.swift

- move unlock confirm and remove votes flow to extrinsic splitter
- support limiting extrinsic batches by manual number of calls per extrinsic in ```ExtrinsicSplitter```
- add limits for number of calls per batch for Ledger wallets

Fix Ledger call vector limits

---

novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionPool.swift

Fixed the type casting of connection stored with `WeakWrapper` in the `connections` dictionary so we can receive the true connection state with subscription.

fix connection cast that always produces nil

---

novawallet/Common/Ledger/LedgerApplication.swift
novawallet/Common/Ledger/MigrationLedgerSubstrateApplication.swift
novawallet/Common/Ledger/SupportedLedgerApps.swift
novawallet/Modules/Ledger/AccountConfirmation/AccountAddFlow/LedgerAddAccountConfirmationInteractor.swift
novawallet/Modules/Ledger/AccountConfirmation/Base/LedgerBaseAccountConfirmationInteractor.swift
novawallet/Modules/Ledger/AccountConfirmation/LedgerAccountConfirmationViewFactory.swift
novawallet/Modules/Ledger/AccountConfirmation/WalletCreateFlow/LedgerWalletAccountConfirmationInteractor.swift
novawallet/Modules/Ledger/Discovery/LedgerDiscoverViewFactory.swift
novawallet/Modules/Ledger/Discovery/Legacy/LedgerDiscoverInteractor.swift
novawallet/Modules/Ledger/Discovery/Legacy/LedgerDiscoverWalletCreateWireframe.swift
novawallet/Modules/Ledger/TxConfirmation/LedgerTxConfirmViewFactory.swift

- if the network supports generic ledger then we need to use migration ledger app

Use migration ledger app for onboarding

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/ExtrinsicService/Substrate/ChainNameOperationFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkDTO.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkSetupFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkViewController.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkViewFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkAddInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractorError.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkEditInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkInteractorProtocols.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkSetupFinishStrategy.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Model/PartialCustomChainModel.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkAddPresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkBasePresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkEditPresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkPresenterProtocols.swift
novawallet/Modules/NetworkManagement/Traits/NetworkNodeConnectingTrait.swift

- refactor CustomNetwork interactors for better flexibility;
- add strategies for chain setup finish;
- add DTO for interactors and presenters for better readability;
- refactor CustomNetworkSetupTrait to CustomNetworkSetupFactory;
- show the chain name and main asset for Substrate networks when the user provides a URL;

Fetch and show network name and main asset by url

---

novawalletTests/Common/Services/ChainRegistry/ConnectionPoolTests.swift

add stub for state getter as we now checking state in `setupConnection` method.

ConnectionPool test fix

---

novawallet/Modules/Vote/Governance/Model/ReferendumAccountVoteLocal.swift
novawalletTests/Modules/Governance/Gov2UnlockScheduleTests.swift
novawalletTests/Modules/Governance/GovernanceUnlocksTestBuilding.swift

- take abstain balance into account when calculating unlock schedule and add test for it #8695883wd
- add test to ensure that no duplication actions are generated in unlock schedule when vote for same track #86955bu54
##

Fix unlock for abstain voting

---

novawallet/Modules/Vote/Governance/Operation/Locks/Gov1LockStateFactory.swift
novawallet/Modules/Vote/Governance/Operation/Locks/Gov2LockStateFactory.swift
novawallet/Modules/Vote/Governance/Operation/Locks/Gov2UnlockReferendum.swift
novawallet/Modules/Vote/Governance/Operation/Locks/GovernanceUnlocksCalculator.swift
novawalletTests/Modules/Governance/Gov2UnlockScheduleTests.swift
novawalletTests/Modules/Governance/GovernanceUnlocksTestBuilding.swift

Previous logic didn't take into account confirm period when estimated unlock time. Now it does as we can go to the confirmation period on the border of the decision period.

Take confirm period into account when estimating unlock time

---

novawallet/Common/Services/PersistExtrinsicService/PersistExtrinsicFactory.swift
novawallet/Common/Services/PersistExtrinsicService/PersistTransferDetails.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+AssetHubSwapMatching.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+CustomFee.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+Fee.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+HydraSwapMatching.swift
novawallet/Common/Services/TransactionSubscription/ExtrinsicProcessor+Matching.swift
novawallet/Modules/AssetConversion/Service/AssetHub/AssetHubTokensConverter.swift
novawallet/Modules/OperationDetails/Model/OperationTransferModel.swift
novawallet/Modules/OperationDetails/OperationDataProviders/OperationDetailsTransferProvider.swift
novawallet/Modules/OperationDetails/ViewModel/OperationDetailsViewModelFactory.swift
novawallet/Modules/Transfer/TransferConfirm/OnChain/TransferEvmOnChainConfirmInteractor.swift
novawallet/Modules/Transfer/TransferConfirm/OnChain/TransferOnChainConfirmInteractor.swift

- Parse the transfer extrinsic to find the 'AssetTxPaymentPallet.assetTxFeePaidEvent' event
- Use the 'assetId' from the event as the fee asset
- Adapt the 'OperationDetails' module to show the fee in a custom asset

Show fee in a custom asset for OperationDetails module

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicOperationFactory.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicServiceFactory.swift
novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/ExtrinsicFeeEstimatingWrapperFactory.swift
novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/ExtrinsicFeeEstimationProtocol.swift
novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/ExtrinsicFeeEstimationRegistry.swift
novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/Hydra/HydraExtrinsicFeeInstaller.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTransferService.swift
novawallet/Modules/AssetConversion/Service/AssetConversionFlowState.swift
novawallet/Modules/AssetConversion/Service/HydraDx/HydraFlowStateStore.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmViewFactory.swift
novawalletIntegrationTests/AutocompounDelegateStakeTests.swift
novawalletIntegrationTests/ExtrinsicServiceTests.swift
novawalletTests/Modules/DApps/DAppOperationConfirm/DAppOperationConfirmTests.swift

- Store weak 'HydraFlowStates' inside of shared 'HydraFlowStateStore'
- Keep flows alive until the end of flow by storing strong refs in ExtrinsicFeeEstimationRegistry
- Use hydra swap state to get current fee currency
- Determine if we need a setCurrency call depending on current fee currency and new one

refactor swap params and flow state logic

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Foundation/String+Helpers.swift
novawallet/Common/Extension/Foundation/String+Trimming.swift
novawallet/Modules/Vote/Governance/SwipeGov/SwipeGov/Polkassembly/PolkassemblyKeys.swift
novawallet/Modules/Vote/Governance/SwipeGov/SwipeGov/SwipeGovPresenter.swift
novawalletTests/Common/Extensions/StringTrimmingTests.swift

As we had issues with the special symbols in the secrets we quote the whole secret. So, on the client before returning the secret to use it is trimmed to get rid of redundant quotes

Fix Polkassembly api key

---

novawallet/Modules/Transfer/TransferConfirm/TransferConfirmCrossChainViewFactory.swift
novawallet/Modules/Transfer/TransferConfirm/TransferConfirmOnChainViewFactory.swift
novawallet/Modules/Transfer/TransferSetup/CrossChain/TransferSetupPresenterFactory+CrossChain.swift
novawallet/Modules/Transfer/TransferSetup/OnChain/TransferSetupPresenterFactory+OnChain.swift
novawallet/Modules/Transfer/Validation/TransferDataValidatorFactory.swift

Pass the destination chain utility asset info to `TransferDataValidatorFactory` so it can be used in `receiverHasAccountProvider` instead of the origin utility asset.

Fix self-sufficiency check on cross-chain transfer

---

novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicSenderResolution/Proxy/ProxyResolutionPathFinder.swift
novawallet/Common/Services/Proxy/ChainProxySyncService.swift

- applied transitive closure to detect nested proxies
- add support for intermediate proxieds edges in the signing paths
##

Nested proxies

---

novawallet/Common/ViewModel/RemoteImageViewModel.swift
novawallet/Modules/DApp/DAppBrowser/StateMachine/PolkadotExtensionStates/DAppBrowserSigningState.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppEthereumConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppEthereumSignBytesInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Proccessing.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Protocol.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmViewFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppSignBytesConfirmInteractor.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppExtrinsicBuilderOperationFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppOperationRequest.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppParsedExtrinsic.swift
novawallet/Modules/DApp/Model/PolkadotExtensionProtocol/PolkadotExtensionExtrinsic.swift
novawallet/Modules/DApp/Model/PolkadotExtensionProtocol/PolkadotExtensionSignerResult.swift
novawallet/Modules/DApp/WalletConnect/Model/WalletConnectSignModelFactory.swift
novawallet/Modules/DApp/WalletConnect/States/WalletConnectStateSigning.swift
novawalletTests/Modules/DApps/DAppOperationConfirm/DAppOperationConfirmTests.swift

- add support for ```withSignedTransaction``` and ```metadataHash``` in the Polkadot Extension signing request
- integrated metadata hash factory to the ```DAppExtrinsicBuilderOperationFactory```
- extended Polkadot Extension signing response with ```signedExtrinsic``` field to allow wallet to replace the extrinsic

Support Generic Ledger in DApp Browser

---

novawallet/Common/Services/Proxy/ChainProxySyncService.swift
novawallet/Common/Storage/WalletsUpdateMediator.swift
novawalletTests/Common/Storage/WalletUpdateMediatorTests.swift
novawalletTests/Helper/AccountGenerator.swift

Current issue was that if nested proxies are added that point to each other (cyclic dependecy) the removal algorithm didn't remove them since each of the wallets had existing wallet that used it. Now we remove a proxied wallet if there is no non proxied wallet reachable from it that is not also being removed.

Remove cyclic proxieds

---

novawallet/Common/Services/CloudBackup/CloudBackupServiceFactory.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupSecretsExporting.swift
novawallet/Common/Services/CloudBackup/Model/CloudBackupValidating.swift
novawalletTests/Common/Services/CloudBackup/CloudBackupSyncTests.swift
novawalletTests/Common/Services/CloudBackup/MockCloudBackupOperationFactory.swift
novawalletTests/Common/Services/CloudBackup/MockCloudBackupServiceFactory.swift

- ensure that a wallet participating in the backup with ```.secret``` type has private key
- ensure that a wallet participating in the backup with ```.ledger``` type has derivation path in the one of the chain accounts
- ensure that a wallet participating in the backup with ```.genericLedger``` type has substrate derivation path
- if broken wallet is detected then backup is not applied
##

Improve validation before Cloud backup application

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Substrate/AssetConverters/CrosschainAssetConversionFactory.swift
novawallet/Common/Substrate/Types/AssetConversionPallet/AssetConversionPallet.swift
novawallet/Common/Substrate/Types/Xcm/V4/XcmJunctionV4.swift
novawallet/Common/Substrate/Types/Xcm/V4/XcmV4.swift
novawallet/Common/Substrate/Types/Xcm/V4/XcmV4Multilocation.swift
novawallet/Modules/AssetConversion/Service/AssetHub/AssetHubTokensConverter.swift
novawallet/Modules/Transfer/TransferSetup/OnChain/OnChainTransferSetupPresenter.swift

[Runtime upgrade](https://github.com/polkadot-fellows/runtimes/releases/tag/v1.3.4) introduced breaking change in the encoding. The PR introduces V4 Multiplication support and switches `AssetConversion.AssetId` to it.

Support xcm v4 multilocation for asset conversion

---

novawallet/Common/Model/Xcm/XcmAssetTransfer.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTransferService+Compose.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTransferService.swift
novawallet/Common/Substrate/Calls/Xcm/XcmPalletTransfer.swift
novawallet/Modules/Transfer/TransferSetup/CrossChain/CrossChainTransferSetupPresenter.swift

Add support for `transfer_assets` xcm type that is currently the way to send xcm transfers from Moonbeam/Moonriver

Add support for new xcm type

---

novawallet/Common/Network/JSONRPC/RemoteStateCallRequest.swift
novawallet/Common/Services/ExtrinsicService/Substrate/FeeManaging/ExtrinsicNativeFeeEstimator.swift

New runtime upgrade on wested broke fee calculation due to type rename. This PR uses type derivation from v15 metadata runtime api and fallbacks to hardcoded one in case there is no v15 metadata support

Derive fee type from runtime api instead of hardcoding value

---

novawallet/Common/Services/AssetExchange/Common/AssetExchangeQuote.swift
novawallet/Modules/Swaps/Base/Model/SwapMaxModel.swift
novawallet/Modules/Swaps/Base/SwapBasePresenter.swift
novawallet/Modules/Swaps/Setup/Model/SwapPreferredFeeAssetModel.swift
novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift
novawallet/Modules/Swaps/Validation/SwapDataValidatorFactory.swift
novawallet/Modules/Swaps/Validation/SwapErrorPresentable.swift
novawallet/Modules/Swaps/Validation/SwapErrorPresentableParams.swift
novawallet/Modules/Swaps/Validation/SwapModel.swift
novawallet/en.lproj/Localizable.strings

Current validation logic contained redundant and hard to read checks. Refactored it to remove redundancy and made it more readable. The validations are the following:
- fee loaded;
- has sufficient balance: enough balance to spend, enough balance to spend and pay fee, enough balance to pay fee in native asset, can pay delivery fee, check that account holding not sufficient assets will have at least ed after the swap;
- not violating min native balance paying fee;
- recipient account can receive tokens: final amount is not less than ed, for not self-sufficient asset there is a provider;
- for multihop swaps: all segments except last one must have an outcome that is greater then min balance;
- check for dust remaining
- request quote and compare with current one to detect significant …

Refactor validations for swaps

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/OperatingSystemApi.swift
novawallet/Modules/Swaps/Execution/SwapExecutionInteractor.swift
novawallet/Modules/Swaps/Execution/SwapExecutionViewFactory.swift

Currently for long swaps (> 30 seconds) a user might run into an issue when application goes to the inactive state due to screen idling. The issue is solved by disabling idle timer during swap execution.

Prevent screen sleep during swap

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Helpers/AddressConversion.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Proccessing.swift

Allow both chain specific addresses and generic substrate addresses when signing operation in DApp browser

Allow generic address in DApp

---

novawallet/Common/Protocols/YourWalletsPresentable.swift
novawallet/Modules/Staking/StakingProxy/Add/StakingSetupProxyPresenter.swift
novawallet/Modules/Transfer/TransferSetup/TransferSetupPresenter.swift
novawallet/Modules/YourWallets/YourWalletsPresenter.swift
novawallet/Modules/YourWallets/YourWalletsProtocols.swift

After new card layout implementation an assumption that presented view controller is presenting view controller for the next modal presentanted controller is not true anymore. This PR removes the assumption for YourWallets presentable protocol but there can be more cases.

Fix YouWallets Presentable

---

novawallet/Modules/DApp/DAppBrowser/DAppBrowserTabList/DAppBrowserTabListViewFactory.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserTabList/View/DAppBrowserTabListViewModelFactory.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserWidget/DAppBrowserWidgetViewController.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserWidget/DAppBrowserWidgetViewFactory.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserWidget/Model/DAppBrowserWidgetModel.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserWidget/Model/DAppBrowserWidgetViewModelFactory.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserWidget/View/DAppBrowserWidgetView.swift
novawallet/Modules/DApp/DAppList/ViewModel/DAppListViewModelFactory/DAppIconViewModelFactory.swift

PR adds support for icons (or favicons) for both `DAppBrowserWidget` and `DAppBrowserTabList` modules.

add dapp icons for browser widget and tabs manager

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/ViewController/ModalPicker/ModalPickerFactory.swift
novawallet/Common/ViewController/ModalPicker/ModalPickerPresentationController.swift
novawallet/Common/ViewController/ModalPicker/ModalPickerPresentationFactory.swift
novawallet/Common/ViewController/ModalPicker/ModalPickerViewController.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupPresenter.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupWireframe.swift

This PR introduces a short-time fix for `ModalPickerViewController` dismissal behavior by synchronizing dismiss and delegate calls via completion closure.
- Introduce `ModalPickerPresentationController` that is identical to `ModalPickerPresentationController` except of dismissing logic
- Introduce `ModalPickerPresentationFactory`

Fix ModalPicker

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/Subscription/MythosStakingLocalStorageSubscriber.swift
novawallet/Common/EventCenter/Events/EraStakersInfoChanged.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStaking+StoragePath.swift
novawallet/Common/Substrate/Types/MythosStaking/MythosStakingPallet+Candidates.swift
novawallet/Common/Substrate/Types/Session/SessionPallet+Path.swift
novawallet/Common/Substrate/Types/Session/SessionPallet.swift
novawallet/Modules/Staking/Operations/MythosStaking/MythosActiveCollators.swift
novawallet/Modules/Staking/Operations/MythosStaking/MythosCollatorOperationFactory.swift
novawallet/Modules/Staking/Services/EraValidatorsService/Collators/ParachainStakingCollatorService.swift
novawallet/Modules/Staking/Services/EraValidatorsService/MythosStaking/MythosCollatorService+Fetch.swift
novawallet/Modules/Staking/Services/EraValidatorsService/MythosStaking/MythosCollatorService.swift
novawallet/Modules/Staking/Services/EraValidatorsService/MythosStaking/MythosCollatorServiceProtocol.swift
novawallet/Modules/Staking/Services/EraValidatorsService/MythosStaking/MythosSessionCollators.swift
novawallet/Modules/Staking/Services/EraValidatorsService/Validators/EraValidatorService.swift
novawalletIntegrationTests/MythosStaking/MythosCollatorsTests.swift

Add `MythosCollatorService` responsible for syncing session collators to display in the interface for a user to select and use in the rewards calculation service

Mythos session collators sync service

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Foundation/URL+Helpers.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserPresenter.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserProtocols.swift
novawallet/Modules/DApp/DAppBrowser/DAppBrowserViewController.swift
novawalletTests/Common/Helpers/URLOriginTests.swift
novawalletTests/Mocks/ModuleMocks.swift

This PR moves current URL update logic for the DApp browser to the `webView:didCommit:` from the observer to fix url/title spoofing problem. However we still allow to update url from the observer when previous and current origins are the same - some dapps may use js scripts to navigate between pages that prevent delegate call.

[CU-8697j1xuw] Fix address bar spoofing issue

---

novawallet/Common/URLHandling/Parsing/OpenGovernanceUrlParsingService.swift

Currently, universal link requires chainId parameter in it. Current PR allows to open Polkadot by default if there is no chainId in the link.

[CU-8696auqzn] Open polkadot governance by default from the universal link

---

novawallet/Modules/PayCard/Mercuryo/Hooks/MercuryoCardHookFactory.swift
novawallet/Modules/PayCard/Mercuryo/MercuryoCardResourceProvider.swift

`payment_method` and `fix_payment_method` query params are removed from widget URL according to mercuryo team suggestions.

remove widget url params

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/SubstrateSdk/RuntimeMetadata+Internal.swift
novawallet/Common/Network/JSONRPC/RemoteStateCallRequest.swift
novawallet/Common/Operation/StateCallOperationFactory.swift
novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeFetchOperationFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/PolkadotInflationPredictionFactory.swift
novawallet/Modules/Staking/Services/RewardCalculatorService/RelayChain/PolkadotRewardParamsService.swift
novawalletIntegrationTests/StateCall/StateCallTests.swift

Currently, state call request is always executed on the last known by the node block. However, there are certain case where one wants to execute query requests on the certain block. For example, such block hash might be received on the state subscription update. The PR introduces an option to provide block hash to the `StateCallRequestFactory`.

Add support of the block hash in the state call

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/AssetExchange/AssetHubExchange/AssetsHubExchangeProvider.swift
novawallet/Common/Services/AssetExchange/HydraExchange/AssetsHydraExchangeProvider.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicStatusService/ExtrinsicStatusService.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicStatusService/ExtrinsicStatusServiceInput.swift
novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicStatusService/SubstrateExtrinsicStatus.swift
novawallet/Common/Substrate/Types/CallDispatchErrorDecoder.swift
novawallet/Common/Substrate/Types/EventRecord.swift
novawalletIntegrationTests/ExtrinsicStatusFetch/ExtrinsicStatusFetchTests.swift

Currently, the error returned from `ExtrinsicSubmissionMonitor` is in raw format and it is hard to understand why an extrinsic failed. The PR introduces automatic error parsing based on the runtime.

Add support for error parsing in ExtrinsicStatusService

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/ChainRegistry/LocalChain/ChainModel.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkDTO.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkProtocols.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkSetupFactory.swift
novawallet/Modules/NetworkManagement/CustomNetwork/CustomNetworkViewController.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkAddInteractor.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkBaseInteractorError.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Interactor/CustomNetworkSetupFinishStrategy.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Model/CustomNetworkType.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkAddPresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkBasePresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkEditPresenter.swift
novawallet/Modules/NetworkManagement/CustomNetwork/Presenter/CustomNetworkPresenterProtocols.swift

Currently if a network is added from preconfigured list the options is has only used and derived ones are ignored preventing from cases when evm address support is derived from runtime. The PR introduces the logic that merges the options from preconfigured network and derived network.
Also PR fixes that logic that marks network as evm only it is ethereumBased and has no runtime in the preconfigured network model

[CU-8697y3wrn] Fix adding evm based network from preconfigured

---

novawallet/Modules/PayCard/Mercuryo/Hooks/MercuryoCardHookFactory.swift
novawallet/Modules/PayCard/Mercuryo/MercuryoCardResourceProvider.swift

removed `fix_currency` and `fiat_currency` param according to mercuryo team suggestions.
changed `currency` param to `currencies`.

Fix Mercuryo Widget params

---

novawallet/Modules/AssetPriceChart/AssetPriceChartInteractor.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartViewController.swift

This PR adds cheap fix for library bug that crashes the app with out-of-bounds error.
Clear highlighted indexes to prevent renderer crashes. The renderer attempts to highlight indexes from previous datasets, which can cause out-of-range errors when switching from multiple to single datasets.
Reference: https://github.com/ChartsOrg/Charts/issues/5154

Fix charts lib crash

---

novawallet/Common/Services/Multistaking/Multistaking+Model.swift
novawallet/Common/Services/Multistaking/Multistaking+Mythos.swift
novawallet/Common/Services/Multistaking/MythosMultistakingUpdateService.swift

Current approach of determining waiting state lead to a situation where current session might change while indexer is still indexing and in result a user will see inactive state. Also, waiting state on the dashboard is not consistent with active state on the details.
New solution uses directly session collators to determine the active state on the dashboard instead of relaying on the indexer.

Use session collators to determine Mythos staking state

---

novawallet/Modules/AssetDetails/AssetDetailsViewController.swift
novawallet/Modules/AssetDetails/Container/ContainerProtocols.swift
novawallet/Modules/AssetDetails/Container/ContainerViewController.swift
novawallet/Modules/AssetDetails/View/AssetDetailsViewLayout.swift

This PR adds animated layout changes for the draggable history sheet when balance widget is expanding or collapsing. 
Additionally, to prevent early frame minimization that would be visible to users, we no longer use `compactHeight`. The difference between using `containerSize` vs. `compactHeight` is demonstrated in the screen recordings.
Using `compactHeight`
https://github.com/user-attachments/assets/8255f508-c24f-4d62-af31-b5f5e3a94ab7
Using `containerSize`
https://github.com/user-attachments/assets/006f7a7b-7fc0-4afe-a13a-6226fee60d47

History draggable layout change on balance widget operations

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/UIKit/Style/StackTitleValueIconView+Style.swift
novawallet/Modules/AssetDetails/AssetDetailsPresenter.swift
novawallet/Modules/AssetDetails/AssetDetailsProtocols.swift
novawallet/Modules/AssetDetails/AssetDetailsViewController.swift
novawallet/Modules/AssetDetails/Model/AssetDetailsBalanceModel.swift
novawallet/Modules/AssetDetails/View/AssetDetailsBalanceWidget.swift
novawallet/Modules/AssetDetails/View/AssetDetailsStyles.swift
novawallet/Modules/AssetDetails/View/AssetDetailsViewModelFactory.swift
novawallet/Modules/AssetDetails/View/StackTitleValueIconView.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartPresenter.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartViewController.swift
novawallet/Modules/AssetPriceChart/Factory/AssetPriceChartViewFactory.swift
novawallet/Modules/AssetPriceChart/Factory/AssetPriceChartViewModelFactory.swift
novawallet/Modules/Currency/View/CurrencyViewController.swift
novawallet/Modules/Currency/View/CurrencyViewLayout.swift

This PR contains fixes for bugs found during pre-release testing:
- Use original price decimal to calculate price change. Previously, we used values of `Double` type received from the chart. Due to precision differences, the resulting values were incorrect. To resolve this problem, we now store all prices by timestamp using a dictionary. This way we can retrieve the original price for any selected entry and use it to calculate price change accurately.
Described difference is demonstrated in **SCREEN RECORDINGS** section.
- Add haptic feedback for the long press `began` state.
- Disable highlighting for the balance widget's total cell.
- Hide chevron and disable expanding/collapsing behavior for zero balances.
- Fix header fonts and insets on the `Currency` screen.
Additionally:
- The …

Fix price chart and asset details bugs

---

novawallet/Modules/AssetDetails/AssetDetailsPresenter.swift
novawallet/Modules/AssetDetails/AssetDetailsProtocols.swift
novawallet/Modules/AssetDetails/AssetDetailsViewController.swift
novawallet/Modules/AssetDetails/View/AssetDetailsViewLayout.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartInteractor.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartPresenter.swift
novawallet/Modules/AssetPriceChart/AssetPriceChartProtocols.swift

This PR adds state-notifying logic for module output. Using this state, the parent module determines if the chart should be shown or not.

Hide chart if price is not available

---

novawallet/Common/Model/ChainRegistry/LocalChain/ChainModel.swift
novawallet/Modules/DApp/DAppBrowser/StateMachine/DAppBrowserStateDataSource.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Proccessing.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppOperationConfirmInteractorError.swift

- don't provide genesis hash for pure ethereum accounts
- remove unnecessary check for signed extensions during extrinsic confirmation

Fix dapp corner cases

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Extension/Operation/CompoundOperationWrapper+Add.swift
novawallet/Common/Extension/Operation/CompoundOperationWrapper+Dependency.swift
novawallet/Common/Extension/Operation/Operation+Dependency.swift
novawallet/Common/Model/StatemineAsset/StatemineAssetSerializer.swift
novawallet/Common/Services/AssetConversion/AssetHub/AssetHubTokensConverter.swift
novawallet/Common/Substrate/AssetConverters/ChargeAssetTxSerializer.swift
novawallet/Common/Substrate/Extension/AssetConversionTxPayment.swift
novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Proccessing.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppExtrinsicBuilderOperationFactory.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppParsedAsset.swift
novawallet/Modules/DApp/DAppOperationConfirm/Model/DAppParsedExtrinsic.swift

Current implementation allows fee payment in custom asset via DApp Browser only for the Asset Hubs. The PR introduces an option of setting the assetId for any network where ChargeAssetTxPayment extension exists. However, as the app can't match local asset for non AH cases the fee is displayed in the native asset but payed in one provided in the assetId field.

Fallback for assetId usage in DApp

---

novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmInteractor+Proccessing.swift

Current implementation could still inject fee token even for cases where fee calculation is custom token is not available. The PR introduce the manual check that fee calculation is available in the given chain and token

Fix polimec fee calc

---

novawallet/Common/Ledger/LedgerConnectionManager.swift
novawallet/Common/Ledger/LedgerTransport.swift
novawalletTests/Common/Ledger/LedgerTransportTests.swift

Previously the MTU was set to minimal value (23) when sending data to Ledger device. The PR introduces the logic that derives negotiated MTU value that is much higher than minimum one. For example, for iPhone XS negotiated MTU is 156 bytes. That allows faster data transmission to Ledger. The signing time is now approx. 3x faster than previously

Ledger upload optimization

---

novawallet/Common/Helpers/Scheduler.swift

The PR adds clamping for milliseconds value, preventing it from overflowing `Int` during conversion from `Double`.

Fix scheduler crash

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Model/BlockWeights.swift
novawallet/Common/Model/SubstrateAlias.swift
novawallet/Common/Model/Xcm/XcmTransfers.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmCrosschainFeeCalculator.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmDynamicCrosschainFeeCalculator.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmExecuteDerivator.swift
novawallet/Common/Services/ExtrinsicService/Substrate/Xcm/XcmTransferService.swift
novawallet/Common/Substrate/AssetOperations/AssetFungibilityPreservationProvider.swift
novawallet/Common/Substrate/Operations/DryRun/DryRunOperationFactory.swift
novawallet/Common/Substrate/Operations/StateCall/SubstrateRuntimeApiOperationFactory.swift
novawallet/Common/Substrate/Operations/XcmPaymentApi/XcmPayment.swift
novawallet/Common/Substrate/Operations/XcmPaymentApi/XcmPaymentOperationFactory.swift
novawallet/Common/Substrate/Types/Xcm/V4/XcmV4Asset.swift
novawallet/Common/Substrate/Types/Xcm/V4/XcmV4Instruction.swift
novawalletIntegrationTests/XcmTransfers/XcmExecuteFeeCalculatorTests.swift

The PR introduces `XcmExecuteDerivator` a new call builder for xcm transactions that builds xcm program manually for each type of the transfer. This allow to pay all the fees from the amount being sent. Previously we had an issue that one can't pay delivery fee from the sending amount and also can't send all amount from the account.
Note: Will refactor xcm program construction in a separate PR by moving the logic from the call builder to the new xcm builder entity.

Introduce execute call builder

---

novawallet/Modules/Staking/CollatorStaking/SelectCollators/CollatorStakingSelectPresenter.swift

The PR adds filtering logic for displayed collator list in collator staking flow. Excluded collators now are not presented in the list, but still could be found and selected via search.
https://github.com/user-attachments/assets/b601826d-aa11-4ba5-be17-f20d43fb09c9

Don't display excluded collators for staking

---

novawallet/Common/Services/WalletConnect/WalletConnectService.swift

The PR fixes long WC request time after WiFi/LTE change by calling forced connection restart if reconnection suggested by WS engine.

Fix long WC request time after WiFi/LTE change

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Substrate/Calls/ParachainStaking/ParaStkCalls.swift
novawallet/Modules/Staking/Parachain/Model/DelegationCallWrapper.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeConfirm/ParaStkStakeConfirmInteractor.swift
novawallet/Modules/Staking/Parachain/ParaStkStakeSetup/ParaStkStakeSetupInteractor.swift

The deprecated `delegate` call has been removed from [Parachain Staking pallet](https://github.com/moonbeam-foundation/moonbeam/pull/3215). The PR introduces support for `delegate_with_autocompound_call`. Since UI doesn't support autocompound yet the values are set to zero correspondingly. Also PR ensures backward compatability for chains which haven't upgrade yet.
##

Add support delegate_with_autocompound for Parachain Staking [CU-8698ghttz]

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/Services/WebSocketService/StorageSubscription/CallbackBatchStorageSubscription+Alias.swift
novawallet/Common/Substrate/Types/AccountInfo.swift
novawallet/Modules/Swaps/Base/SwapBaseInteractor.swift
novawallet/Modules/Swaps/Base/SwapBasePresenter.swift
novawallet/Modules/Swaps/Setup/SwapSetupInteractor.swift
novawallet/Modules/Swaps/Validation/SwapDataValidatorFactory.swift
novawallet/Modules/Swaps/Validation/SwapModel.swift

MYTH token can situate on Mythos chain as native asset and as non sufficient asset on PAH. When a user doesn't have at least ED in DOT on PAH MYTH token can't be stored on PAH. Thus we need also track account info on destination chain and validate whether the receiving account meet ED requirement before crosschaining non sufficient asset to the destination account.
##

Fix non sufficient swap validation

---

novawallet/Common/Services/CloudBackup/Model/NSPredicate+CloudBackup.swift
novawallet/Common/Services/DelegatedAccounts/Repositories/ProxyAccountsRepository.swift
novawallet/Common/Storage/WalletsUpdateMediator.swift

This PR addresses the following bugs:
- Failure to redirect to welcome screen after removing the last wallet
- Cloud backup error after adding a multisig account
- Incorrect filtering for detected proxies
- Incomplete removal of linked proxies/multisig accounts after delegate account deletion
- Failure to switch to another wallet after current wallet removal
Additionally, the PR updates WalletUpdateMediator, changing its logic to handle all delegated accounts instead of just proxied ones.

Multisig detection fixes

---

novawallet/Modules/Swaps/Setup/SwapSetupPresenter.swift

The PR fixes the issue when the receive token is not set after swap retry

Restore asset receive when retrying the swap

---

novawallet/Common/Services/AssetExchange/AssetExchangePathFilter.swift

The PR fixes an issue where non sufficient assets can be transfered via xcm as first swap segment. As the result assets might be trapped. The PR introduces constraints that forbid any non single segment paths containing insufficient asset

Forbid insufficient assets for non single paths &8699cj7mb

---

novawallet/Common/Services/ExtrinsicService/Substrate/ExtrinsicServiceFactory.swift

Fee calculation is currently broken for multisig approval on EVM networks. This PR fixes the issue.
The issue is caused by the dummy account response used for call weight estimation. The response has its crypto type manually set to `sr25519`. This crypto type is later used to generate the extrinsic signature, but EVM networks expect an ethereum's `ecdsa` signature instead. The fix adds a check for chain type to select the correct crypto type either for EVM or Substrate networks.
The recording shows there are fee calculated for multisig operations in both EVM and Substrate networks
https://github.com/user-attachments/assets/8fe9d512-a394-4893-88c4-9a1d368f199f

Fee calculation for EVM multisig approval

---

novawallet/Common/RampProvider/Providers/RampURLFactory/MercuryoRampURLFactory.swift
novawalletTests/Modules/Wallet/PurchaseProviders/WalletPurchaseProvidersTests.swift

The PR adds `merchant_transaction_id` query param for mercuryo provider URL. The param is required for signature check.

Mercuryo url params fix

---

NovaPushNotificationServiceExtension/Handlers/Multisig/CommonMultisigHandler.swift
NovaPushNotificationServiceExtension/en.lproj/Localizable.strings
novawallet/Common/Extension/Foundation/String+Split.swift

The PR extends common notification body construction logic with delegated account formatting. Also changed part separators to `.newLine` according to mockups.

handle delegated account formatting

---

novawallet/Modules/Staking/Dashboard/Model/StakingDashboardBuilder.swift

#869a6742n
The PR fixes typo in the staking dashboard that mixed-up sync state for onchain and off chain. That prevented sync to complete after pull to refresh due to paused networks which are indefinitely synced onchain

Fix staking dashboard pull to refresh

---

novawallet/Common/DataProvider/Subscription/AccountLocalStorageSubscriber.swift
novawallet/Common/Extension/Foundation/Predicate/NSPredicate+Filter.swift
novawallet/Common/Helpers/AccountProviderFactory.swift

When there are wallet changes after staking details opened then accounts discovered for controller and stash might be getting cleared. For example, when there are discovered proxies on Kusama the for Polkadot staking AccountProvider might report changes not in the Polkadot.
The issue is fixed by providing more strict filters for AccountProvider to not notify about non actual wallets

Fix controller check for redeem operation

---

novawallet/Common/Services/ChainRegistry/ChainFilterStrategy.swift
novawallet/Common/Services/ServiceCoordinator.swift
novawalletTests/Common/Helpers/ChainFilterStrategyTests.swift
novawalletTests/Helper/ChainModelGenerator.swift

The PR adds `hasDelegatedAccounts` filter strategy and integrates it for `DelegatedAccountSyncService`.

Add delegated accounts chain filter strategy

---

novawallet/Modules/NovaMainAppContainer/NovaMainAppContainerViewController.swift

The PR excludes custom modals from manual layout updates in `NovaMainAppContainerViewController`.

Fix modals weird layout on dapp browser widget changes

---

novawallet.xcodeproj/project.pbxproj
novawallet/Common/DataProvider/NPoolsLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/Sources/Rewards/SubqueryTotalRewardSource.swift
novawallet/Common/DataProvider/Sources/Rewards/WeaklyAnalyticsRewardSource.swift
novawallet/Common/DataProvider/StakingAnalyticsLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/StakingRewardsLocalSubscriptionFactory.swift
novawallet/Common/DataProvider/Subscription/NPoolsLocalStorageHandler.swift
novawallet/Common/DataProvider/Subscription/NPoolsLocalStorageSubscriber.swift
novawallet/Common/DataProvider/Subscription/StakingAnalyticsLocalStorageSubscriber.swift
novawallet/Common/DataProvider/Subscription/StakingAnalyticsLocalSubscriptionHandler.swift
novawallet/Common/DataProvider/Subscription/StakingRewardsLocalHandler.swift
novawallet/Common/DataProvider/Subscription/StakingRewardsLocalSubscriber.swift
novawallet/Common/Model/ChainRegistry/LocalChain/LocalChainExternalApi.swift
novawallet/Common/Model/ChainRegistry/RemoteChain/RemoteChainExternalApi.swift
novawallet/Common/Network/Subquery/SubqueryRewardAggregatingWrapperFactory.swift
novawallet/Common/Services/PayoutRewardsService/PayoutValidatorsForNominatorFactory.swift
novawallet/Modules/Staking/StakingMain/Mythos/MythosStakingDetailsInteractor.swift
novawallet/Modules/Staking/StakingMain/NominationPools/StakingNPoolsInteractor.swift
novawallet/Modules/Staking/StakingMain/Parachain/StakingParachainInteractor+Subscription.swift
novawallet/Modules/Staking/StakingMain/Relaychain/StakingRelaychainInteractor+Subscription.swift
novawallet/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewFactory.swift
novawalletIntegrationTests/PayoutRewardsServiceTests.swift
novawalletTests/Common/DataProvider/RewardDataSourceTests.swift
novawalletTests/Helper/ChainModelGenerator.swift
novawalletTests/Mocks/DataProviders/StakingAnalyticsLocalSubscriptionFactoryStub.swift

The PR adds support for `staking-rewards` external API list. The values received from the indexers are merged in result value.
`staking-rewards` API is used in place of old `staking` API for rewards and payouts fetch.

[AH-Migration] Aggregate staking rewards APIs

---

novawallet/Modules/DApp/DAppAuthSettings/ViewModel/DAppsAuthViewModelFactory.swift

The PR fixes auth removal logic by using new `identifier` field for view model instead of old `dAppId`.

Fix DApp auth removal

---

novawallet/Info.plist

There is a community feature request to make encrypted iCloud file visible in the iCloud Drive (Files -> iCloud Drive -> Backup (with Nova Wallet icon)). The PR enables visibility of the app's backup directory

10.3.8 Make iCloud Backup visible
